export type Language = { code: string; name: string; native: string };

const ALL_LANGUAGES: Language[] = [
  { code: "en", name: "English", native: "English" },
  { code: "hi", name: "Hindi", native: "हिन्दी" },
  { code: "mr", name: "Marathi", native: "मराठी" },
  { code: "ne", name: "Nepali", native: "नेपाली" },
  { code: "bn", name: "Bengali", native: "বাংলা" },
  { code: "gu", name: "Gujarati", native: "ગુજરાતી" },
  { code: "pa", name: "Punjabi", native: "ਪੰਜਾਬੀ" },
  { code: "or", name: "Odia", native: "ଓଡ଼ିଆ" },
  { code: "as", name: "Assamese", native: "অসমীয়া" },
  { code: "ta", name: "Tamil", native: "தமிழ்" },
  { code: "te", name: "Telugu", native: "తెలుగు" },
  { code: "kn", name: "Kannada", native: "ಕನ್ನಡ" },
  { code: "ml", name: "Malayalam", native: "മലയാളം" },
  { code: "si", name: "Sinhala", native: "සිංහල" },
  { code: "sd", name: "Sindhi", native: "سنڌي" },
  { code: "ks", name: "Kashmiri", native: "कॉशुर" },
  { code: "mai", name: "Maithili", native: "मैथिली" },
  { code: "bho", name: "Bhojpuri", native: "भोजपुरी" },
  { code: "raj", name: "Rajasthani", native: "राजस्थानी" },
  { code: "gom", name: "Konkani", native: "कोंकणी" },
  { code: "mni", name: "Manipuri", native: "মৈতৈলোন্" },
  { code: "sa", name: "Sanskrit", native: "संस्कृतम्" },
  { code: "dz", name: "Dzongkha", native: "རྫོང་ཁ" },
  { code: "ur", name: "Urdu", native: "اردو" },
  { code: "fa", name: "Persian", native: "فارسی" },
  { code: "ps", name: "Pashto", native: "پښتو" },
  { code: "ar", name: "Arabic", native: "العربية" },
  { code: "he", name: "Hebrew", native: "עברית" },
  { code: "ku", name: "Kurdish", native: "Kurdî" },
  { code: "my", name: "Burmese", native: "မြန်မာစာ" },
  { code: "th", name: "Thai", native: "ไทย" },
  { code: "lo", name: "Lao", native: "ລາວ" },
  { code: "km", name: "Khmer", native: "ខ្មែរ" },
  { code: "vi", name: "Vietnamese", native: "Tiếng Việt" },
  { code: "id", name: "Indonesian", native: "Bahasa Indonesia" },
  { code: "ms", name: "Malay", native: "Bahasa Melayu" },
  { code: "jv", name: "Javanese", native: "Basa Jawa" },
  { code: "su", name: "Sundanese", native: "Basa Sunda" },
  { code: "fil", name: "Filipino", native: "Filipino" },
  { code: "tl", name: "Tagalog", native: "Tagalog" },
  { code: "ceb", name: "Cebuano", native: "Cebuano" },
  { code: "zh", name: "Chinese", native: "中文" },
  { code: "yue", name: "Cantonese", native: "粵語" },
  { code: "ja", name: "Japanese", native: "日本語" },
  { code: "ko", name: "Korean", native: "한국어" },
  { code: "mn", name: "Mongolian", native: "Монгол" },
  { code: "bo", name: "Tibetan", native: "བོད་སྐད་" },
  { code: "ka", name: "Georgian", native: "ქართული" },
  { code: "hy", name: "Armenian", native: "Հայերեն" },
  { code: "az", name: "Azerbaijani", native: "Azərbaycan" },
  { code: "tr", name: "Turkish", native: "Türkçe" },
  { code: "uz", name: "Uzbek", native: "Oʻzbek" },
  { code: "kk", name: "Kazakh", native: "Қазақша" },
  { code: "ky", name: "Kyrgyz", native: "Кыргызча" },
  { code: "tg", name: "Tajik", native: "Тоҷикӣ" },
  { code: "tk", name: "Turkmen", native: "Türkmen" },
  { code: "ru", name: "Russian", native: "Русский" },
  { code: "uk", name: "Ukrainian", native: "Українська" },
  { code: "be", name: "Belarusian", native: "Беларуская" },
  { code: "pl", name: "Polish", native: "Polski" },
  { code: "cs", name: "Czech", native: "Čeština" },
  { code: "sk", name: "Slovak", native: "Slovenčina" },
  { code: "bg", name: "Bulgarian", native: "Български" },
  { code: "sr", name: "Serbian", native: "Српски" },
  { code: "hr", name: "Croatian", native: "Hrvatski" },
  { code: "bs", name: "Bosnian", native: "Bosanski" },
  { code: "sl", name: "Slovenian", native: "Slovenščina" },
  { code: "mk", name: "Macedonian", native: "Македонски" },
  { code: "sq", name: "Albanian", native: "Shqip" },
  { code: "el", name: "Greek", native: "Ελληνικά" },
  { code: "ro", name: "Romanian", native: "Română" },
  { code: "hu", name: "Hungarian", native: "Magyar" },
  { code: "de", name: "German", native: "Deutsch" },
  { code: "nl", name: "Dutch", native: "Nederlands" },
  { code: "af", name: "Afrikaans", native: "Afrikaans" },
  { code: "fy", name: "Frisian", native: "Frysk" },
  { code: "da", name: "Danish", native: "Dansk" },
  { code: "sv", name: "Swedish", native: "Svenska" },
  { code: "no", name: "Norwegian", native: "Norsk" },
  { code: "is", name: "Icelandic", native: "Íslenska" },
  { code: "fi", name: "Finnish", native: "Suomi" },
  { code: "et", name: "Estonian", native: "Eesti" },
  { code: "lv", name: "Latvian", native: "Latviešu" },
  { code: "lt", name: "Lithuanian", native: "Lietuvių" },
  { code: "ga", name: "Irish", native: "Gaeilge" },
  { code: "gd", name: "Scottish Gaelic", native: "Gàidhlig" },
  { code: "cy", name: "Welsh", native: "Cymraeg" },
  { code: "br", name: "Breton", native: "Brezhoneg" },
  { code: "eu", name: "Basque", native: "Euskara" },
  { code: "ca", name: "Catalan", native: "Català" },
  { code: "gl", name: "Galician", native: "Galego" },
  { code: "es", name: "Spanish", native: "Español" },
  { code: "pt", name: "Portuguese", native: "Português" },
  { code: "it", name: "Italian", native: "Italiano" },
  { code: "fr", name: "French", native: "Français" },
  { code: "oc", name: "Occitan", native: "Occitan" },
  { code: "co", name: "Corsican", native: "Corsu" },
  { code: "sc", name: "Sardinian", native: "Sardu" },
  { code: "la", name: "Latin", native: "Latina" },
  { code: "sw", name: "Swahili", native: "Kiswahili" },
  { code: "am", name: "Amharic", native: "አማርኛ" },
  { code: "ti", name: "Tigrinya", native: "ትግርኛ" },
  { code: "yo", name: "Yoruba", native: "Yorùbá" },
  { code: "ig", name: "Igbo", native: "Igbo" },
  { code: "ha", name: "Hausa", native: "Hausa" },
  { code: "zu", name: "Zulu", native: "isiZulu" },
  { code: "xh", name: "Xhosa", native: "isiXhosa" },
  { code: "st", name: "Sesotho", native: "Sesotho" },
  { code: "sn", name: "Shona", native: "chiShona" },
  { code: "ny", name: "Chichewa", native: "Chichewa" },
  { code: "rw", name: "Kinyarwanda", native: "Ikinyarwanda" },
  { code: "lg", name: "Luganda", native: "Luganda" },
  { code: "so", name: "Somali", native: "Soomaali" },
  { code: "om", name: "Oromo", native: "Afaan Oromoo" },
  { code: "mg", name: "Malagasy", native: "Malagasy" },
  { code: "ee", name: "Ewe", native: "Eʋegbe" },
  { code: "wo", name: "Wolof", native: "Wolof" },
  { code: "ff", name: "Fula", native: "Fulfulde" },
  { code: "yo_ng", name: "Yoruba (Nigerian)", native: "Èdè Yorùbá" },
  { code: "haw", name: "Hawaiian", native: "ʻŌlelo Hawaiʻi" },
  { code: "mi", name: "Maori", native: "Te Reo Māori" },
  { code: "sm", name: "Samoan", native: "Gagana Samoa" },
  { code: "to", name: "Tongan", native: "Lea Faka-Tonga" },
  { code: "fj", name: "Fijian", native: "Na Vosa Vakaviti" },
  { code: "ty", name: "Tahitian", native: "Reo Tahiti" },
  { code: "qu", name: "Quechua", native: "Runa Simi" },
  { code: "ay", name: "Aymara", native: "Aymar aru" },
  { code: "gn", name: "Guarani", native: "Avañe'ẽ" },
  { code: "nv", name: "Navajo", native: "Diné bizaad" },
  { code: "cr", name: "Cree", native: "ᓀᐦᐃᔭᐍᐏᐣ" },
  { code: "iu", name: "Inuktitut", native: "ᐃᓄᒃᑎᑐᑦ" },
];

export const LANGUAGES = ALL_LANGUAGES;

export const LANG_KEY = "zv-lang";

export function findLanguage(code: string): Language {
  return LANGUAGES.find((l) => l.code === code) ?? LANGUAGES[0];
}
