const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),os=require("node:os");const{chromium}=require(process.env.PLAYWRIGHT_CORE_PATH||"playwright-core");const base=process.env.BASE_URL||"http://localhost:3000";
function exe(){const root=path.join(os.homedir(),".cache","ms-playwright"),v=fs.readdirSync(root).find(x=>x.startsWith("chromium_headless_shell"));for(const d of["chrome-linux","chrome-linux64"]){const p=path.join(root,v,d,"headless_shell");if(fs.existsSync(p))return p;}throw Error("no chromium")}
async function fill(p,name){const g=p.getByRole("group",{name:"Birth details",exact:true});await g.getByLabel("Full name",{exact:true}).fill(name);await g.getByLabel("Date of birth",{exact:true}).fill("2001-08-31");await g.getByLabel("Time of birth",{exact:true}).fill("15:04");await g.getByRole("button",{name:"Enter coordinates / time zone manually",exact:true}).click();await g.getByLabel("Place of birth",{exact:true}).fill("Nellore");await g.getByLabel("Latitude",{exact:true}).fill("14.4499");await g.getByLabel("Longitude",{exact:true}).fill("79.987");await g.getByLabel("Time zone",{exact:true}).fill("Asia/Kolkata")}
(async()=>{const b=await chromium.launch({executablePath:exe(),args:["--no-sandbox"]}),ctx=await b.newContext({viewport:{width:1440,height:900}}),p=await ctx.newPage(),errors=[];p.on("pageerror",e=>errors.push(e.message));try{await p.goto(base,{waitUntil:"networkidle"});const hs=await p.locator("#calculators h3").allInnerTexts();assert.equal(hs.length,11);assert.deepEqual(hs.slice(0,2),["Build Your Horoscope","Marriage Horoscope Matching"]);assert.equal(await p.locator('#calculators [aria-disabled="true"]').count(),0);const y=await p.locator("#calculators").evaluate(e=>e.getBoundingClientRect().top+scrollY);await p.getByRole("button",{name:"Build Chart",exact:true}).first().click();await p.waitForTimeout(700);const scrolled=await p.evaluate(()=>scrollY);assert.ok(Math.abs(scrolled-y)<180,`scroll ${scrolled} target ${y}`);console.log('PASS all 11 tiles available; hero Build Chart scrolls to calculator grid');
const configs=[
 {href:'/calculators/kaal-sarp',submit:'Check Kaal Sarp →',head:'Kaal Sarp Analysis',verify:async()=>{await p.getByText('Planet order from Rahu',{exact:true}).waitFor();await p.getByText(/of 7 classical planets lie/).waitFor();}},
 {href:'/calculators/mangal-dosha',submit:'Check Mangal Dosha →',head:'Kuja / Mangal Dosha',verify:async()=>{await p.getByText('From Lagna',{exact:true}).waitFor();await p.getByText('Marriage context beyond Mars',{exact:true}).waitFor();}},
 {href:'/calculators/sade-sati',submit:'Check my Sade Sati →',head:'Sade Sati',verify:async()=>{await p.getByText('Phase timeline',{exact:true}).waitFor();await p.getByText('Your natal Saturn',{exact:true}).waitFor();}}
];
for(const [i,c] of configs.entries()){await p.goto(base+c.href,{waitUntil:'networkidle'});await fill(p,`Final Browser ${i+1}`);const resp=p.waitForResponse(r=>r.url().includes('/api/')&&r.request().method()==='POST');await p.getByRole('button',{name:c.submit,exact:true}).click();const api=await resp;assert.equal(api.status(),201,await api.text());await p.getByRole('heading',{name:new RegExp(c.head)}).waitFor();await c.verify();await p.getByRole('link',{name:'Full horoscope',exact:true}).waitFor();console.log(`PASS ${c.head}: real submission and comprehensive saved report`)}
await p.setViewportSize({width:390,height:844});await p.reload({waitUntil:'networkidle'});const w=await p.evaluate(()=>({p:document.documentElement.scrollWidth,v:innerWidth}));assert.ok(w.p<=w.v+2,JSON.stringify(w));assert.deepEqual(errors,[]);console.log('PASS mobile no overflow; no page errors');console.log('All final dedicated calculator browser tests passed.');}finally{await ctx.close();await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
