/* Run: PLAYWRIGHT_CORE_PATH=/path/to/playwright-core node tests/nakshatra-dasha.e2e.cjs */
const assert=require("node:assert/strict");const fs=require("node:fs"),path=require("node:path"),os=require("node:os");const{chromium}=require(process.env.PLAYWRIGHT_CORE_PATH||"playwright-core");const base=process.env.BASE_URL||"http://localhost:3000";
function browserPath(){if(process.env.CHROMIUM_PATH)return process.env.CHROMIUM_PATH;const root=path.join(os.homedir(),".cache","ms-playwright");const ver=fs.readdirSync(root).find(p=>p.startsWith("chromium_headless_shell"));for(const dir of["chrome-linux","chrome-linux64"]){const c=path.join(root,ver,dir,"headless_shell");if(fs.existsSync(c))return c;}throw Error("Chromium not found");}
async function fill(page,name){const g=page.getByRole("group",{name:"Birth details",exact:true});await g.getByLabel("Full name",{exact:true}).fill(name);await g.getByLabel("Date of birth",{exact:true}).fill("2001-08-31");await g.getByLabel("Time of birth",{exact:true}).fill("15:04");await g.getByRole("button",{name:"Enter coordinates / time zone manually",exact:true}).click();await g.getByLabel("Place of birth",{exact:true}).fill("Nellore");await g.getByLabel("Latitude",{exact:true}).fill("14.4499");await g.getByLabel("Longitude",{exact:true}).fill("79.987");await g.getByLabel("Time zone",{exact:true}).fill("Asia/Kolkata");}
(async()=>{const browser=await chromium.launch({executablePath:browserPath(),args:["--no-sandbox"]});const context=await browser.newContext({viewport:{width:1440,height:1000}});const errors=[];try{const page=await context.newPage();page.on("pageerror",e=>errors.push(e.message));await page.goto(base,{waitUntil:"networkidle"});
const headings=await page.locator("#calculators h3").allInnerTexts();assert.deepEqual(headings.slice(0,2),["Build Your Horoscope","Marriage Horoscope Matching"]);assert.ok(headings.includes("Nakshatra & Rashi")&&headings.includes("Vimshottari Dasha"));const boxes=await page.locator("#calculators h3").evaluateAll(hs=>hs.map(h=>h.closest(".card").getBoundingClientRect()));assert.equal(boxes[0].top,boxes[1].top);assert.ok(boxes[1].left>boxes[0].left);assert.ok(boxes.every(b=>Math.abs(b.width-boxes[0].width)<2));const av=await page.locator("#calculators a").count(),up=await page.locator('#calculators [aria-disabled="true"]').count();assert.equal(av+up,headings.length);assert.ok((await page.locator("#calculators").innerText()).includes(`${av} calculators ready now, ${up} more`));console.log(`PASS tiles: Build left, Marriage right, ${av} ready / ${up} upcoming`);

// NAKSHATRA
await page.locator("#calculators a",{hasText:"Nakshatra & Rashi"}).click();await page.waitForURL("**/calculators/nakshatra-rashi");await fill(page,"Browser Nak Test");let response=page.waitForResponse(r=>r.url().endsWith("/api/nakshatra-rashi")&&r.request().method()==="POST");await page.getByRole("button",{name:"Find my Nakshatra →",exact:true}).click();let api=await response;assert.equal(api.status(),201,await api.text());await page.waitForURL(`**/calculators/nakshatra-rashi/${(await api.json()).slug}`);await page.getByRole("heading",{name:"Browser Nak Test",exact:true}).waitFor();await page.getByRole("heading",{name:"Shravana",exact:true}).waitFor();await page.getByText("51.7% of Shravana",{exact:false}).waitFor();console.log("PASS Nakshatra: exact Shravana-3 report rendered with progress");
await page.getByRole("button",{name:"⭐ Nakshatra & padas",exact:true}).click();assert.equal(await page.getByText("YOUR PADA",{exact:true}).count(),1);await page.getByText("Syllable: Khe",{exact:true}).waitFor();console.log("PASS all four padas shown and only Pada 3 active");
await page.getByRole("button",{name:"☽ Moon sign",exact:true}).click();await page.getByRole("heading",{name:/Makara/}).waitFor();await page.getByText("Strengths of Capricorn",{exact:true}).waitFor();
await page.getByRole("button",{name:"🪷 Avakhada & Panchang",exact:true}).click();await page.getByText("Shravana - 3",{exact:true}).waitFor();await page.getByText("22:18:17",{exact:true}).waitFor();
await page.getByRole("button",{name:"🔯 Tara & lucky factors",exact:true}).click();assert.equal(await page.locator("tbody tr").count(),9);await page.getByText("Yellow Sapphire",{exact:false}).first().waitFor();
await page.getByRole("button",{name:"🪔 Guidance",exact:true}).click();await page.getByText("Do not wear",{exact:false}).waitFor();await page.getByRole("button",{name:"📖 Method",exact:true}).click();await page.getByText("not medical",{exact:false}).waitFor();console.log("PASS Nakshatra: Rashi, Avakhada, Panchang, Tara, lucky factors, remedies and limits");

// DASHA
await page.goto(base+"/#calculators",{waitUntil:"networkidle"});await page.locator('#calculators a[href="/calculators/vimshottari-dasha"]').click();await page.waitForURL("**/calculators/vimshottari-dasha");await fill(page,"Browser Dasha Test");response=page.waitForResponse(r=>r.url().endsWith("/api/vimshottari-dasha")&&r.request().method()==="POST");await page.getByRole("button",{name:"Calculate my dasha timeline →",exact:true}).click();api=await response;assert.equal(api.status(),201,await api.text());await page.waitForURL(`**/calculators/vimshottari-dasha/${(await api.json()).slug}`);await page.getByRole("heading",{name:"Browser Dasha Test",exact:true}).waitFor();await page.getByText("Moon — 4 years 9 months 29 days",{exact:true}).waitFor();await page.getByText("Running: Rahu → Venus → Jupiter",{exact:true}).waitFor();console.log("PASS Dasha: balance and current MD→AD→PD rendered");
await page.getByRole("button",{name:"Pratyantar: Jupiter",exact:true}).click();await page.getByRole("heading",{name:/Rahu → Venus → Jupiter/}).waitFor();await page.getByText(/Remedies for this period/).waitFor();await page.getByRole("button",{name:"⏳ Full timeline",exact:true}).click();await page.getByText("Your life timeline",{exact:true}).waitFor();const running=page.getByText("RUNNING",{exact:true});assert.equal(await running.count(),1);const nowBadges=page.getByText("NOW",{exact:true});assert.ok(await nowBadges.count()>=1);console.log("PASS Dasha interactive timeline opens current period with details");
await page.getByRole("button",{name:"🔮 Next 5 years",exact:true}).click();const periods=page.locator("details");const periodCount=await periods.count();assert.ok(periodCount>=20);await periods.first().locator("summary").click();await page.getByText("Benefits",{exact:true}).first().waitFor();await page.getByText("Challenges",{exact:true}).first().waitFor();await page.getByRole("button",{name:"📖 Method",exact:true}).click();await page.getByText("365.25 days",{exact:false}).waitFor();console.log(`PASS Dasha next-five-year list (${periodCount} periods), benefits/challenges and method`);
await page.getByRole("button",{name:"✦ Summary",exact:true}).click();const link=page.getByRole("link",{name:"Open the complete horoscope for this chart →",exact:true});assert.equal((await fetch(base+await link.getAttribute("href"))).status,200);await page.reload({waitUntil:"networkidle"});await page.getByText("Running: Rahu → Venus → Jupiter",{exact:true}).waitFor();console.log("PASS saved Dasha report reloads and links to full horoscope");
await page.setViewportSize({width:390,height:844});await page.reload({waitUntil:"networkidle"});const widths=await page.evaluate(()=>({page:document.documentElement.scrollWidth,viewport:innerWidth}));assert.ok(widths.page<=widths.viewport+2,JSON.stringify(widths));console.log("PASS mobile report has no horizontal overflow");assert.deepEqual(errors,[]);console.log("All Nakshatra + Dasha browser tests passed.");}finally{await context.close();await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
