export type PlanetId = "Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu";

export const PLANETS: PlanetId[] = ["Sun", "Moon", "Mars", "Mercury", "Jupiter", "Venus", "Saturn", "Rahu", "Ketu"];

export interface SignInfo {
  en: string;
  sa: string;
  glyph: string;
  lord: PlanetId;
  element: "Fire" | "Earth" | "Air" | "Water";
  quality: "Movable" | "Fixed" | "Dual";
  gender: "Masculine" | "Feminine";
  guna: string;
  purushartha: string;
  direction: string;
  varna: string;
  vashya: string;
  archetype: string;
  symbol: string;
  strengths: string;
  challenges: string;
  body: string;
}

export const SIGNS: SignInfo[] = [
  { en: "Aries", sa: "Mesha", glyph: "♈", lord: "Mars", element: "Fire", quality: "Movable", gender: "Masculine", guna: "Tamasic", purushartha: "Dharma", direction: "East", varna: "Kshatriya", vashya: "Chatushpada", archetype: "Pioneering and courageous. Quick to act, competitive and self-driven. Natural initiator who loves challenges and leadership.", symbol: "Ram", strengths: "Courageous; energetic; pioneering; enthusiastic; direct; confident; dynamic; independent; honest; quick-witted; adventurous", challenges: "Impulsive; impatient; short-tempered; aggressive; self-centred; reckless; restless; poor finisher", body: "Head, brain, face" },
  { en: "Taurus", sa: "Vrishabha", glyph: "♉", lord: "Venus", element: "Earth", quality: "Fixed", gender: "Feminine", guna: "Rajasic", purushartha: "Artha", direction: "South", varna: "Vaishya", vashya: "Chatushpada", archetype: "Steady, patient and sensual. Loves comfort, beauty, music and security. Builds wealth slowly and holds on firmly.", symbol: "Bull", strengths: "Reliable; patient; practical; devoted; artistic; loyal; sensual; persistent; grounded; affectionate; good with money", challenges: "Stubborn; possessive; materialistic; lazy; self-indulgent; resistant to change; jealous", body: "Face, throat, neck, mouth" },
  { en: "Gemini", sa: "Mithuna", glyph: "♊", lord: "Mercury", element: "Air", quality: "Dual", gender: "Masculine", guna: "Rajasic", purushartha: "Kama", direction: "West", varna: "Shudra", vashya: "Nara (Human)", archetype: "Curious, witty and communicative. Versatile mind that loves learning, travel, trade and conversation.", symbol: "Couple holding mace and lyre", strengths: "Intelligent; witty; adaptable; eloquent; curious; youthful; sociable; quick learner; humorous; versatile", challenges: "Inconsistent; nervous; superficial; indecisive; gossipy; restless; scattered focus", body: "Shoulders, arms, lungs, hands" },
  { en: "Cancer", sa: "Karka", glyph: "♋", lord: "Moon", element: "Water", quality: "Movable", gender: "Feminine", guna: "Sattvic", purushartha: "Moksha", direction: "North", varna: "Brahmin", vashya: "Jalachara (Water)", archetype: "Nurturing, emotional and protective. Deeply attached to home, mother and family. Intuitive and imaginative.", symbol: "Crab", strengths: "Caring; intuitive; loyal; imaginative; protective; sympathetic; tenacious; homely; emotionally intelligent", challenges: "Moody; over-sensitive; clingy; insecure; manipulative when hurt; holds grudges; worrying", body: "Chest, breasts, heart, stomach" },
  { en: "Leo", sa: "Simha", glyph: "♌", lord: "Sun", element: "Fire", quality: "Fixed", gender: "Masculine", guna: "Sattvic", purushartha: "Dharma", direction: "East", varna: "Kshatriya", vashya: "Vanachara (Wild)", archetype: "Royal, generous and dignified. Natural leader who seeks recognition, creativity and self-expression.", symbol: "Lion", strengths: "Generous; warm-hearted; creative; courageous; loyal; authoritative; noble; charismatic; protective", challenges: "Proud; arrogant; domineering; vain; stubborn; attention-seeking; intolerant", body: "Heart, upper back, spine, stomach" },
  { en: "Virgo", sa: "Kanya", glyph: "♍", lord: "Mercury", element: "Earth", quality: "Dual", gender: "Feminine", guna: "Rajasic", purushartha: "Artha", direction: "South", varna: "Vaishya", vashya: "Nara (Human)", archetype: "Analytical, precise and service-oriented. Perfectionist with a sharp eye for detail, health and order.", symbol: "Maiden in a boat holding grain and fire", strengths: "Analytical; diligent; modest; practical; helpful; methodical; intelligent; health-conscious; discriminating", challenges: "Overcritical; worrying; fussy; perfectionist; shy; nervous; sceptical", body: "Intestines, abdomen, digestive system" },
  { en: "Libra", sa: "Tula", glyph: "♎", lord: "Venus", element: "Air", quality: "Movable", gender: "Masculine", guna: "Rajasic", purushartha: "Kama", direction: "West", varna: "Shudra", vashya: "Nara (Human)", archetype: "Balanced, charming and diplomatic. Seeks harmony, justice, partnership and beauty in all things.", symbol: "Man holding a balance", strengths: "Diplomatic; fair; charming; artistic; sociable; peaceful; romantic; cooperative; refined", challenges: "Indecisive; people-pleasing; dependent; superficial; avoids confrontation; indulgent", body: "Kidneys, lower back, pelvis, skin" },
  { en: "Scorpio", sa: "Vrishchika", glyph: "♏", lord: "Mars", element: "Water", quality: "Fixed", gender: "Feminine", guna: "Tamasic", purushartha: "Moksha", direction: "North", varna: "Brahmin", vashya: "Keeta (Insect)", archetype: "Intense, secretive and transformative. Deep researcher with powerful will, magnetism and occult interest.", symbol: "Scorpion", strengths: "Determined; passionate; perceptive; resourceful; loyal; brave; investigative; magnetic; resilient", challenges: "Jealous; secretive; vindictive; obsessive; suspicious; controlling; stubborn", body: "Reproductive organs, excretory system" },
  { en: "Sagittarius", sa: "Dhanu", glyph: "♐", lord: "Jupiter", element: "Fire", quality: "Dual", gender: "Masculine", guna: "Sattvic", purushartha: "Dharma", direction: "East", varna: "Kshatriya", vashya: "Nara / Chatushpada", archetype: "Humane and philosophical. Dynamic and hasty or impulsive. Open and fair minded. Jovial and Optimistic. Religious and sacrificing nature.", symbol: "Bow and Arrow", strengths: "Humane; hasty; dynamic; jovial; sincere; optimistic; versatile; open and fair minded; philosophical; frank; visionary; active; enterprising; religious; sacrificing nature; god fearing; honest; humble; sympathetic; energetic; inspiring", challenges: "Over anxious; restless; indecisive; callous; tactless; careless; boastful; irresponsible; apt to exaggerate; habit of preaching; argumentative; uncommitted", body: "Hips, thighs, liver" },
  { en: "Capricorn", sa: "Makara", glyph: "♑", lord: "Saturn", element: "Earth", quality: "Movable", gender: "Feminine", guna: "Tamasic", purushartha: "Artha", direction: "South", varna: "Vaishya", vashya: "Jalachara / Chatushpada", archetype: "Ambitious, disciplined and practical. Patient climber who values duty, structure, status and tradition.", symbol: "Crocodile / sea-goat", strengths: "Ambitious; disciplined; responsible; patient; practical; prudent; hardworking; organised; loyal; persevering", challenges: "Pessimistic; rigid; cold; calculating; miserly; workaholic; stubborn", body: "Knees, joints, bones, skin" },
  { en: "Aquarius", sa: "Kumbha", glyph: "♒", lord: "Saturn", element: "Air", quality: "Fixed", gender: "Masculine", guna: "Tamasic", purushartha: "Kama", direction: "West", varna: "Shudra", vashya: "Nara (Human)", archetype: "Humanitarian, original and intellectual. Independent thinker who serves the collective and embraces innovation.", symbol: "Man holding a water pot", strengths: "Humanitarian; original; inventive; intellectual; friendly; independent; idealistic; tolerant; scientific", challenges: "Detached; rebellious; unpredictable; aloof; stubborn; eccentric; emotionally distant", body: "Calves, ankles, circulation" },
  { en: "Pisces", sa: "Meena", glyph: "♓", lord: "Jupiter", element: "Water", quality: "Dual", gender: "Feminine", guna: "Sattvic", purushartha: "Moksha", direction: "North", varna: "Brahmin", vashya: "Jalachara (Water)", archetype: "Compassionate, spiritual and imaginative. Dreamy, intuitive and self-sacrificing with a mystical outlook.", symbol: "Two fish swimming in opposite directions", strengths: "Compassionate; intuitive; artistic; gentle; spiritual; selfless; imaginative; adaptable; wise; forgiving", challenges: "Escapist; over-emotional; indecisive; gullible; lacks boundaries; lazy; easily deceived", body: "Feet, lymphatic system" },
];

export interface PlanetInfo {
  sa: string;
  short: string;
  glyph: string;
  color: string;
  nature: "Benefic" | "Malefic";
  exalt: [number, number];
  own: number[];
  mt: [number, number, number];
  friends: PlanetId[];
  neutral: PlanetId[];
  enemies: PlanetId[];
  karaka: string;
  deity: string;
  adhidevata: string;
  pratyadhidevata: string;
  gem: string;
  metal: string;
  day: string;
  color2: string;
  direction: string;
  number: number;
  grain: string;
  mantra: string;
  years: number;
  meanSpeed: number;
  body: string;
  significations: string;
  remedies: string[];
  avoid: string[];
  aspects: number[];
  digbalaHouse: number;
  naisargika: number;
  gender: string;
  element: string;
}

export const PLANET_INFO: Record<PlanetId, PlanetInfo> = {
  Sun: { sa: "Surya", short: "Su", glyph: "☉", color: "#f59e0b", nature: "Malefic", exalt: [0, 10], own: [4], mt: [4, 0, 20], friends: ["Moon", "Mars", "Jupiter"], neutral: ["Mercury"], enemies: ["Venus", "Saturn", "Rahu", "Ketu"], karaka: "Soul, father, authority, government, vitality, ego, fame", deity: "Agni", adhidevata: "Shiva (Ishvara)", pratyadhidevata: "Agni", gem: "Ruby (Manik)", metal: "Gold / Copper", day: "Sunday", color2: "Red / Orange", direction: "East", number: 1, grain: "Wheat", mantra: "Om Hraam Hreem Hraum Sah Suryaya Namah", years: 6, meanSpeed: 0.9856, body: "Heart, bones, right eye, spine", significations: "Atma (soul), father, king, government, authority, leadership, self-confidence, health, vitality, eyesight, fame, political power, doctors, gold", remedies: ["Offer water (Arghya) to the rising Sun daily", "Recite Aditya Hridayam Stotra", "Respect father and elders", "Donate wheat and jaggery on Sundays"], avoid: ["Ego clashes with authority figures", "Arrogance and dominance", "Skipping breakfast / irregular routine"], aspects: [7], digbalaHouse: 10, naisargika: 60, gender: "Male", element: "Fire" },
  Moon: { sa: "Chandra", short: "Mo", glyph: "☽", color: "#e2e8f0", nature: "Benefic", exalt: [1, 3], own: [3], mt: [1, 3, 30], friends: ["Sun", "Mercury"], neutral: ["Mars", "Jupiter", "Venus", "Saturn"], enemies: ["Rahu", "Ketu"], karaka: "Mind, mother, emotions, public, liquids, comfort", deity: "Varuna (Apas)", adhidevata: "Parvati (Uma)", pratyadhidevata: "Apas (Water)", gem: "Pearl (Moti)", metal: "Silver", day: "Monday", color2: "White / Silver", direction: "North-West", number: 2, grain: "Rice", mantra: "Om Shraam Shreem Shraum Sah Chandraya Namah", years: 10, meanSpeed: 13.176, body: "Mind, blood, fluids, left eye, breasts", significations: "Manas (mind), mother, emotions, peace, public, popularity, travel, water, milk, nourishment, fertility, imagination, memory", remedies: ["Worship Lord Shiva on Mondays", "Keep a silver item and drink water from silver vessel", "Serve and respect mother", "Donate rice, milk or white cloth on Mondays"], avoid: ["Emotional over-reaction", "Sleeping late / irregular sleep", "Disrespecting women"], aspects: [7], digbalaHouse: 4, naisargika: 51.43, gender: "Female", element: "Water" },
  Mars: { sa: "Mangala", short: "Ma", glyph: "♂", color: "#ef4444", nature: "Malefic", exalt: [9, 28], own: [0, 7], mt: [0, 0, 12], friends: ["Sun", "Moon", "Jupiter"], neutral: ["Venus", "Saturn"], enemies: ["Mercury", "Rahu"], karaka: "Energy, courage, siblings, land, property, surgery", deity: "Skanda (Kartikeya)", adhidevata: "Skanda", pratyadhidevata: "Bhumi (Earth)", gem: "Red Coral (Moonga)", metal: "Copper", day: "Tuesday", color2: "Red", direction: "South", number: 9, grain: "Red lentils (Masoor)", mantra: "Om Kraam Kreem Kraum Sah Bhaumaya Namah", years: 7, meanSpeed: 0.524, body: "Muscles, blood, marrow, head injuries", significations: "Courage, strength, younger siblings, land, real estate, police, army, engineering, surgery, sports, accidents, fire, weapons, competition", remedies: ["Recite Hanuman Chalisa on Tuesdays", "Donate red lentils and jaggery", "Practice physical exercise to channel energy", "Help younger siblings"], avoid: ["Anger and impulsive decisions", "Risky driving and fights", "Litigation over property"], aspects: [4, 7, 8], digbalaHouse: 10, naisargika: 17.14, gender: "Male", element: "Fire" },
  Mercury: { sa: "Budha", short: "Me", glyph: "☿", color: "#22c55e", nature: "Benefic", exalt: [5, 15], own: [2, 5], mt: [5, 16, 20], friends: ["Sun", "Venus", "Rahu"], neutral: ["Mars", "Jupiter", "Saturn", "Ketu"], enemies: ["Moon"], karaka: "Intellect, speech, trade, learning, friends, skin", deity: "Vishnu", adhidevata: "Vishnu (Narayana)", pratyadhidevata: "Vishnu", gem: "Emerald (Panna)", metal: "Bronze / Brass", day: "Wednesday", color2: "Green", direction: "North", number: 5, grain: "Green gram (Moong)", mantra: "Om Braam Breem Braum Sah Budhaya Namah", years: 17, meanSpeed: 0.9856, body: "Nervous system, skin, speech, lungs", significations: "Intelligence, communication, writing, mathematics, commerce, accounting, education, humour, maternal uncles, astrology, media, IT", remedies: ["Worship Lord Vishnu / Ganesha on Wednesdays", "Donate green gram and green cloth", "Feed green grass to cows", "Read and study regularly"], avoid: ["Lying and deceitful speech", "Signing papers carelessly", "Overthinking and nervous habits"], aspects: [7], digbalaHouse: 1, naisargika: 25.71, gender: "Neutral", element: "Earth" },
  Jupiter: { sa: "Guru", short: "Ju", glyph: "♃", color: "#facc15", nature: "Benefic", exalt: [3, 5], own: [8, 11], mt: [8, 0, 10], friends: ["Sun", "Moon", "Mars"], neutral: ["Saturn", "Rahu", "Ketu"], enemies: ["Mercury", "Venus"], karaka: "Wisdom, children, guru, wealth, dharma, husband", deity: "Indra", adhidevata: "Brahma", pratyadhidevata: "Indra", gem: "Yellow Sapphire (Pukhraj)", metal: "Gold", day: "Thursday", color2: "Yellow", direction: "North-East", number: 3, grain: "Chana dal (Bengal gram)", mantra: "Om Graam Greem Graum Sah Gurave Namah", years: 16, meanSpeed: 0.0831, body: "Liver, fat, thighs, pancreas", significations: "Wisdom, knowledge, teachers, children, wealth, religion, philosophy, law, banking, husband (for women), fortune, morality, expansion", remedies: ["Worship Lord Vishnu / Dakshinamurthy on Thursdays", "Respect teachers and elders", "Donate turmeric, yellow cloth or chana dal", "Apply saffron / turmeric tilak"], avoid: ["Disrespecting gurus or priests", "Over-indulgence and weight gain", "Arrogance about knowledge"], aspects: [5, 7, 9], digbalaHouse: 1, naisargika: 34.28, gender: "Male", element: "Ether" },
  Venus: { sa: "Shukra", short: "Ve", glyph: "♀", color: "#ec4899", nature: "Benefic", exalt: [11, 27], own: [1, 6], mt: [6, 0, 15], friends: ["Mercury", "Saturn", "Rahu", "Ketu"], neutral: ["Mars", "Jupiter"], enemies: ["Sun", "Moon"], karaka: "Love, marriage, wife, luxury, arts, vehicles", deity: "Shachi (Indrani)", adhidevata: "Indra", pratyadhidevata: "Indrani", gem: "Diamond (Heera) / Opal", metal: "Silver / Platinum", day: "Friday", color2: "White / Pink", direction: "South-East", number: 6, grain: "Rice / white beans", mantra: "Om Draam Dreem Draum Sah Shukraya Namah", years: 20, meanSpeed: 0.9856, body: "Reproductive system, kidneys, face, throat", significations: "Love, romance, spouse (for men), marriage, beauty, art, music, dance, luxury, vehicles, jewellery, comforts, fashion, diplomacy", remedies: ["Worship Goddess Lakshmi on Fridays", "Donate white sweets, curd or perfume", "Keep yourself and surroundings clean and fragrant", "Respect women and spouse"], avoid: ["Over-indulgence in pleasures", "Extravagant spending", "Disrespecting partner"], aspects: [7], digbalaHouse: 4, naisargika: 42.85, gender: "Female", element: "Water" },
  Saturn: { sa: "Shani", short: "Sa", glyph: "♄", color: "#60a5fa", nature: "Malefic", exalt: [6, 20], own: [9, 10], mt: [10, 0, 20], friends: ["Mercury", "Venus", "Rahu"], neutral: ["Jupiter", "Ketu"], enemies: ["Sun", "Moon", "Mars"], karaka: "Longevity, discipline, servants, delays, karma, masses", deity: "Brahma (Prajapati)", adhidevata: "Yama", pratyadhidevata: "Prajapati", gem: "Blue Sapphire (Neelam)", metal: "Iron", day: "Saturday", color2: "Black / Dark blue", direction: "West", number: 8, grain: "Black sesame (Til)", mantra: "Om Praam Preem Praum Sah Shanaischaraya Namah", years: 19, meanSpeed: 0.0335, body: "Bones, teeth, joints, nerves, legs", significations: "Longevity, discipline, hard work, delay, sorrow, servants, labour, masses, democracy, oil, iron, mining, justice, detachment, old age", remedies: ["Light a sesame oil lamp on Saturdays", "Serve the poor, elderly and labourers", "Recite Hanuman Chalisa / Shani Stotra", "Donate black sesame, mustard oil or blankets"], avoid: ["Cheating and shortcuts", "Mistreating servants or workers", "Laziness and procrastination"], aspects: [3, 7, 10], digbalaHouse: 7, naisargika: 8.57, gender: "Neutral", element: "Air" },
  Rahu: { sa: "Rahu", short: "Ra", glyph: "☊", color: "#a78bfa", nature: "Malefic", exalt: [1, 20], own: [10], mt: [2, 0, 30], friends: ["Mercury", "Venus", "Saturn"], neutral: ["Jupiter"], enemies: ["Sun", "Moon", "Mars"], karaka: "Obsession, foreign lands, technology, illusion, sudden events", deity: "Durga", adhidevata: "Kala (Time)", pratyadhidevata: "Sarpa (Serpent)", gem: "Hessonite (Gomed)", metal: "Lead / Mixed metals", day: "Saturday", color2: "Smoky / Dark blue", direction: "South-West", number: 4, grain: "Urad dal (black gram)", mantra: "Om Bhraam Bhreem Bhraum Sah Rahave Namah", years: 18, meanSpeed: 0.0529, body: "Nervous disorders, poisons, skin allergies", significations: "Worldly desires, foreign countries, technology, research, unconventional paths, politics, sudden gains/losses, addictions, maternal grandparents, illusion", remedies: ["Worship Goddess Durga", "Donate to sweepers and outcasts", "Feed dogs, keep a square silver piece", "Recite Rahu mantra 108 times on Saturdays"], avoid: ["Intoxicants and addictions", "Shortcuts and illegal gains", "Deception and over-ambition"], aspects: [5, 7, 9], digbalaHouse: 10, naisargika: 0, gender: "Female", element: "Air" },
  Ketu: { sa: "Ketu", short: "Ke", glyph: "☋", color: "#fb923c", nature: "Malefic", exalt: [7, 20], own: [7], mt: [8, 0, 30], friends: ["Mars", "Venus", "Saturn"], neutral: ["Mercury", "Jupiter"], enemies: ["Sun", "Moon"], karaka: "Liberation, spirituality, detachment, past karma, occult", deity: "Ganesha", adhidevata: "Chitragupta", pratyadhidevata: "Brahma", gem: "Cat's Eye (Lehsunia)", metal: "Mixed metals", day: "Tuesday", color2: "Grey / Multicolour", direction: "North-West", number: 7, grain: "Horse gram (Kulthi)", mantra: "Om Sraam Sreem Sraum Sah Ketave Namah", years: 7, meanSpeed: 0.0529, body: "Nervous system, spine, mysterious ailments", significations: "Moksha (liberation), spirituality, detachment, intuition, occult, mathematics, past-life skills, sudden separation, paternal grandparents, healing", remedies: ["Worship Lord Ganesha", "Feed stray dogs", "Donate blankets and sesame", "Meditate regularly"], avoid: ["Isolation and escapism", "Ignoring health symptoms", "Confusion-driven decisions"], aspects: [5, 7, 9], digbalaHouse: 4, naisargika: 0, gender: "Neutral", element: "Fire" },
};

export interface NakInfo {
  name: string;
  lord: PlanetId;
  deity: string;
  symbol: string;
  gana: "Deva" | "Manushya" | "Rakshasa";
  yoni: string;
  yoniGender: "Male" | "Female";
  nadi: "Adi" | "Madhya" | "Antya";
  syllables: [string, string, string, string];
  nature: string;
  traits: string;
}

const N = (name: string, lord: PlanetId, deity: string, symbol: string, gana: NakInfo["gana"], yoni: string, yoniGender: NakInfo["yoniGender"], nadi: NakInfo["nadi"], syl: string, nature: string, traits: string): NakInfo => ({ name, lord, deity, symbol, gana, yoni, yoniGender, nadi, syllables: syl.split(" ") as [string, string, string, string], nature, traits });

export const NAKSHATRAS: NakInfo[] = [
  N("Ashwini", "Ketu", "Ashwini Kumaras", "Horse's head", "Deva", "Horse", "Male", "Adi", "Chu Che Cho La", "Swift (Kshipra)", "Quick, healing, adventurous, pioneering, youthful and helpful. Loves speed and new beginnings."),
  N("Bharani", "Venus", "Yama", "Yoni (womb)", "Manushya", "Elephant", "Male", "Madhya", "Li Lu Le Lo", "Fierce (Ugra)", "Bearer of burdens; creative, determined, passionate, truthful and able to handle extremes."),
  N("Krittika", "Sun", "Agni", "Razor, flame", "Rakshasa", "Sheep", "Female", "Antya", "A I U E", "Mixed (Mishra)", "Sharp, purifying, ambitious, proud and protective. Cuts through falsehood."),
  N("Rohini", "Moon", "Brahma (Prajapati)", "Ox cart, chariot", "Manushya", "Serpent", "Male", "Antya", "O Va Vi Vu", "Fixed (Dhruva)", "Beautiful, charming, artistic, fertile and materially prosperous."),
  N("Mrigashira", "Mars", "Soma", "Deer's head", "Deva", "Serpent", "Female", "Madhya", "Ve Vo Ka Ki", "Soft (Mridu)", "Searching, curious, gentle, restless and fond of travel and knowledge."),
  N("Ardra", "Rahu", "Rudra", "Teardrop, diamond", "Manushya", "Dog", "Female", "Adi", "Ku Gha Ng Chha", "Sharp (Tikshna)", "Intense, analytical, transformative; storms that clear the way for growth."),
  N("Punarvasu", "Jupiter", "Aditi", "Bow and quiver", "Deva", "Cat", "Female", "Adi", "Ke Ko Ha Hi", "Movable (Chara)", "Renewal, optimism, generosity, simplicity and return of light."),
  N("Pushya", "Saturn", "Brihaspati", "Cow's udder, lotus, arrow", "Deva", "Sheep", "Male", "Madhya", "Hu He Ho Da", "Swift (Kshipra)", "Nourishing, protective, devoted, disciplined — the most auspicious nakshatra."),
  N("Ashlesha", "Mercury", "Nagas (Serpents)", "Coiled serpent", "Rakshasa", "Cat", "Male", "Antya", "Di Du De Do", "Sharp (Tikshna)", "Mystical, perceptive, clever, hypnotic and deeply intuitive."),
  N("Magha", "Ketu", "Pitris (Ancestors)", "Royal throne", "Rakshasa", "Rat", "Male", "Antya", "Ma Mi Mu Me", "Fierce (Ugra)", "Regal, proud, traditional, ancestral blessings and leadership."),
  N("Purva Phalguni", "Venus", "Bhaga", "Front legs of a bed, hammock", "Manushya", "Rat", "Female", "Madhya", "Mo Ta Ti Tu", "Fierce (Ugra)", "Pleasure-loving, creative, affectionate, relaxed and generous."),
  N("Uttara Phalguni", "Sun", "Aryaman", "Back legs of a bed", "Manushya", "Cow", "Male", "Adi", "Te To Pa Pi", "Fixed (Dhruva)", "Reliable, kind, contractual, helpful and devoted to partnerships."),
  N("Hasta", "Moon", "Savitr", "Hand", "Deva", "Buffalo", "Female", "Adi", "Pu Sha Na Tha", "Swift (Kshipra)", "Skilful, witty, industrious, clever with hands, healing touch."),
  N("Chitra", "Mars", "Vishvakarma", "Bright jewel, pearl", "Rakshasa", "Tiger", "Female", "Madhya", "Pe Po Ra Ri", "Soft (Mridu)", "Artistic, glamorous, architectural, designing and charismatic."),
  N("Swati", "Rahu", "Vayu", "Young sprout swaying in the wind, coral", "Deva", "Buffalo", "Male", "Antya", "Ru Re Ro Ta", "Movable (Chara)", "Independent, flexible, diplomatic, business-minded and restless."),
  N("Vishakha", "Jupiter", "Indra-Agni", "Triumphal arch, potter's wheel", "Rakshasa", "Tiger", "Male", "Antya", "Ti Tu Te To", "Mixed (Mishra)", "Goal-oriented, ambitious, determined, single-minded achiever."),
  N("Anuradha", "Saturn", "Mitra", "Lotus, triumphal arch", "Deva", "Deer", "Female", "Madhya", "Na Ni Nu Ne", "Soft (Mridu)", "Devoted, friendly, organised, success through cooperation."),
  N("Jyeshtha", "Mercury", "Indra", "Circular amulet, umbrella, earring", "Rakshasa", "Deer", "Male", "Adi", "No Ya Yi Yu", "Sharp (Tikshna)", "Senior, protective, powerful, responsible and resourceful."),
  N("Mula", "Ketu", "Nirriti", "Bunch of roots tied together, elephant goad", "Rakshasa", "Dog", "Male", "Adi", "Ye Yo Bha Bhi", "Sharp (Tikshna)", "Investigative, goes to the root, philosophical, transformative."),
  N("Purva Ashadha", "Venus", "Apas (Water)", "Elephant tusk, fan, winnowing basket", "Manushya", "Monkey", "Male", "Madhya", "Bhu Dha Pha Dha", "Fierce (Ugra)", "Invincible, proud, persuasive, purifying and optimistic."),
  N("Uttara Ashadha", "Sun", "Vishvedevas", "Elephant tusk, small bed", "Manushya", "Mongoose", "Male", "Antya", "Bhe Bho Ja Ji", "Fixed (Dhruva)", "Universal victory, righteous, principled, enduring success."),
  N("Shravana", "Moon", "Vishnu", "Ear, three footprints", "Deva", "Monkey", "Female", "Antya", "Khi Khu Khe Kho", "Movable (Chara)", "Listener, learned, connected, wise and well-travelled."),
  N("Dhanishta", "Mars", "Eight Vasus", "Drum (Mridanga), flute", "Rakshasa", "Lion", "Female", "Madhya", "Ga Gi Gu Ge", "Movable (Chara)", "Wealthy, musical, rhythmic, generous and ambitious."),
  N("Shatabhisha", "Rahu", "Varuna", "Empty circle, 1000 flowers", "Rakshasa", "Horse", "Female", "Adi", "Go Sa Si Su", "Movable (Chara)", "Healer, secretive, scientific, independent and philosophical."),
  N("Purva Bhadrapada", "Jupiter", "Aja Ekapada", "Swords, front legs of funeral cot", "Manushya", "Lion", "Male", "Adi", "Se So Da Di", "Fierce (Ugra)", "Intense, idealistic, passionate, spiritual transformation."),
  N("Uttara Bhadrapada", "Saturn", "Ahir Budhnya", "Twins, back legs of funeral cot", "Manushya", "Cow", "Female", "Madhya", "Du Tha Jha Na", "Fixed (Dhruva)", "Wise, deep, disciplined, compassionate and self-controlled."),
  N("Revati", "Mercury", "Pushan", "Fish, drum", "Deva", "Elephant", "Female", "Antya", "De Do Cha Chi", "Soft (Mridu)", "Nurturing, gentle, guiding, prosperous and spiritually complete."),
];

export interface BhavaInfo {
  name: string;
  title: string;
  karaka: string;
  karakaGraha: string;
  element: string;
  direction: string;
  joy: string;
  body: string;
  significations: string;
  more: string;
  types: string[];
}

export const BHAVAS: BhavaInfo[] = [
  { name: "Lagna", title: "Self, personality, physical body", karaka: "Self, personality, appearance, constitution", karakaGraha: "Surya", element: "Fire", direction: "East", joy: "Budha", body: "Head, brain, face", significations: "Physical body, health, vitality, fame, temperament, longevity, start of life, head, brain, complexion, character, dignity, self-expression", more: "The Lagna (Ascendant) is the most important point of the horoscope. It represents you — your body, your outlook, your innate strength and the lens through which every other house is experienced. A strong Lagna and Lagna lord protect the entire chart; a weak one makes life a struggle even with good yogas. It is both a Kendra (angle — pillar of strength) and a Trikona (trine — seat of fortune).", types: ["Kendra", "Trikona"] },
  { name: "Dhana", title: "Wealth, family, speech", karaka: "Accumulated wealth, family, speech, food", karakaGraha: "Guru", element: "Earth", direction: "South", joy: "—", body: "Face, eyes (right), mouth, teeth, tongue, throat", significations: "Savings, bank balance, family lineage, speech, voice, food habits, early education, values, right eye, face, truthfulness, jewels, precious possessions", more: "The 2nd house (Dhana Bhava) shows what you accumulate and sustain — money, family bonds, values and the quality of your speech. It is a Maraka (death-inflicting) house for longevity calculations and an Artha (wealth) house. Benefics here give sweet speech and wealth; malefics may give harsh speech or family discord.", types: ["Artha", "Maraka"] },
  { name: "Sahaja", title: "Courage, siblings, communication", karaka: "Courage, younger siblings, efforts, skills", karakaGraha: "Mangala", element: "Air", direction: "West", joy: "Chandra", body: "Arms, shoulders, hands, right ear, collarbone", significations: "Valour, initiative, younger siblings, short journeys, writing, media, communication, hobbies, hands, neighbours, self-effort, determination", more: "The 3rd house (Sahaja / Parakrama Bhava) is the house of personal effort and courage. It is an Upachaya house — it improves with time and malefics like Mars, Saturn and Rahu actually do well here, giving drive and competitive spirit. It governs communication, media, writing and short travel.", types: ["Upachaya", "Kama"] },
  { name: "Sukha", title: "Mother, home, happiness", karaka: "Mother, home, vehicles, inner peace", karakaGraha: "Chandra", element: "Water", direction: "North", joy: "—", body: "Chest, heart, lungs, breasts", significations: "Mother, domestic happiness, property, land, house, vehicles, education (formal), emotional security, comforts, homeland, heart, peace of mind", more: "The 4th house (Sukha / Bandhu Bhava) is the root of the chart — the nadir, the home, the mother and the heart. It is a Kendra and a Moksha house. A well-placed 4th brings property, vehicles, happiness and a peaceful mind; afflictions bring domestic unrest or frequent relocation.", types: ["Kendra", "Moksha"] },
  { name: "Putra", title: "Children, intelligence, creativity", karaka: "Children, intelligence, past-life merit, romance", karakaGraha: "Guru", element: "Fire", direction: "East", joy: "Shukra", body: "Stomach, upper abdomen, liver", significations: "Children, progeny, intellect, creativity, romance, love affairs, speculation, mantras, Purva Punya (merit of past lives), education, students, advisors, stock market", more: "The 5th house (Putra Bhava) is a Trikona — one of the most auspicious houses. It shows your intelligence, creativity, children and the merit you carry from past lives. The 5th lord in a good position blesses one with wisdom, good children and success in speculation.", types: ["Trikona", "Dharma"] },
  { name: "Ripu", title: "Enemies, disease, debts, service", karaka: "Enemies, disease, debt, competition, service", karakaGraha: "Mangala / Shani", element: "Earth", direction: "South", joy: "Mangala", body: "Intestines, lower abdomen, kidneys", significations: "Enemies, litigation, disease, debts, loans, obstacles, service, daily work, employees, pets, maternal uncles, competitive exams, healing professions", more: "The 6th house (Ripu / Shatru Bhava) is a Dusthana (difficult house) but also an Upachaya. Malefics here destroy enemies and help one win competitions and litigation. Benefics may suffer here. It governs daily work, health routines and service.", types: ["Dusthana", "Upachaya", "Artha"] },
  { name: "Kalatra", title: "Marriage, partnerships, spouse", karaka: "Spouse, marriage, partnerships, public dealings", karakaGraha: "Shukra", element: "Air", direction: "West", joy: "—", body: "Kidneys, lower back, pelvis, bladder", significations: "Spouse, marriage, business partners, contracts, public relations, foreign travel, trade, sexual life, open enemies, desire, legal agreements", more: "The 7th house (Kalatra / Yuvati Bhava) is the house of 'the other' — spouse, partners and the public. It is a Kendra and a Kama house, and also a Maraka house. Its condition shows the nature of marriage and partnerships.", types: ["Kendra", "Kama", "Maraka"] },
  { name: "Randhra", title: "Longevity, transformation, secrets", karaka: "Longevity, sudden events, occult, inheritance", karakaGraha: "Shani", element: "Water", direction: "North", joy: "—", body: "Reproductive and excretory organs", significations: "Longevity, death, inheritance, insurance, hidden wealth, occult, research, surgery, chronic illness, sudden events, in-laws, secrets, transformation, tantra", more: "The 8th house (Randhra / Ayu Bhava) is the most mysterious house — longevity, sudden events, hidden matters and deep transformation. A Dusthana, but also a Moksha house that gives research ability, occult insight and inheritance.", types: ["Dusthana", "Moksha"] },
  { name: "Dharma", title: "Fortune, father, religion, higher learning", karaka: "Fortune, father, dharma, guru, long journeys", karakaGraha: "Guru / Surya", element: "Fire", direction: "East", joy: "Surya", body: "Hips, thighs", significations: "Luck, destiny, father, preceptor, religion, philosophy, higher education, law, pilgrimages, long-distance travel, righteousness, grace of God", more: "The 9th house (Dharma / Bhagya Bhava) is the most auspicious Trikona — the house of fortune. The 9th lord is the most benefic planet in any chart. It shows father, guru, beliefs and the grace that flows into your life.", types: ["Trikona", "Dharma"] },
  { name: "Karma", title: "Career, status, actions", karaka: "Career, profession, reputation, authority", karakaGraha: "Surya / Budha / Guru / Shani", element: "Earth", direction: "South", joy: "—", body: "Knees, joints", significations: "Profession, career, status, fame, government, authority, deeds, honour, achievements, employer, public image, father (alternate)", more: "The 10th house (Karma Bhava) is the zenith of the chart — the most powerful Kendra. It shows your profession, your actions in the world and the recognition you earn. Planets here are highly visible in life.", types: ["Kendra", "Upachaya", "Artha"] },
  { name: "Labha", title: "Gains, income, aspirations", karaka: "Gains, income, elder siblings, fulfilment of desires", karakaGraha: "Guru", element: "Air", direction: "West", joy: "Guru", body: "Calves, ankles, left ear", significations: "Income, profits, gains, elder siblings, friends, social networks, wishes, aspirations, awards, large organisations, recovery from illness", more: "The 11th house (Labha Bhava) is the house of gains. Every planet gives good results here as it fulfils desires. It is an Upachaya and Kama house — benefits grow with age.", types: ["Upachaya", "Kama"] },
  { name: "Vyaya", title: "Losses, expenses, liberation, foreign lands", karaka: "Expenses, losses, foreign lands, moksha, sleep", karakaGraha: "Shani", element: "Water", direction: "North", joy: "Shani", body: "Feet, left eye", significations: "Expenditure, losses, foreign residence, hospitals, isolation, bed pleasures, sleep, charity, spirituality, liberation, secret enemies, ashrams, prisons", more: "The 12th house (Vyaya Bhava) is the house of letting go — expenses, sleep, foreign lands and final liberation (Moksha). A Dusthana, yet vital for spiritual growth and settling abroad.", types: ["Dusthana", "Moksha"] },
];

export const DASHA_ORDER: PlanetId[] = ["Ketu", "Venus", "Sun", "Moon", "Mars", "Rahu", "Jupiter", "Saturn", "Mercury"];

export const TITHIS = ["Pratipada", "Dwitiya", "Tritiya", "Chaturthi", "Panchami", "Shashthi", "Saptami", "Ashtami", "Navami", "Dashami", "Ekadashi", "Dwadashi", "Trayodashi", "Chaturdashi", "Purnima"];
export const NITYA_YOGAS = ["Vishkambha", "Priti", "Ayushman", "Saubhagya", "Shobhana", "Atiganda", "Sukarma", "Dhriti", "Shoola", "Ganda", "Vriddhi", "Dhruva", "Vyaghata", "Harshana", "Vajra", "Siddhi", "Vyatipata", "Variyana", "Parigha", "Shiva", "Siddha", "Sadhya", "Shubha", "Shukla", "Brahma", "Indra", "Vaidhriti"];
export const WEEKDAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
export const WEEKDAY_LORD: PlanetId[] = ["Sun", "Moon", "Mars", "Mercury", "Jupiter", "Venus", "Saturn"];
