import type { PlanetId } from "./data";

export const IN_HOUSE: Record<PlanetId, string[]> = {
  Sun: ["Confident, authoritative, strong vitality", "Wealth via government; firm speech", "Courageous, bold, self-made", "Proud of home; domestic friction", "Intelligent, creative leader", "Victorious over enemies, good health", "Dominant partner; ego in marriage", "Hidden power; vitality fluctuates", "Righteous, fortunate, devoted to father", "Fame, status, government favour", "Gains through powerful people", "Spiritual, expenses, foreign links"],
  Moon: ["Charming, emotional, changeable", "Sweet speech, family wealth", "Adventurous mind, frequent travel", "Happy home, mother's blessings", "Imaginative, loving towards children", "Emotional stress, service-minded", "Attractive, caring spouse", "Intuitive, emotionally deep", "Devout, fortunate, pilgrimages", "Public popularity, changing career", "Gains via women and the public", "Dreamy, spiritual, restless sleep"],
  Mars: ["Energetic, angry", "Harsh speech, earns by effort", "Brave, strong initiative", "Property gains, domestic friction", "Sharp intellect, sporty", "Destroys enemies, competitive", "Passionate, marital friction", "Accident-prone, research power", "Crusader for beliefs", "Commanding career, engineering", "Gains via courage and land", "Hidden enemies, heavy expenses"],
  Mercury: ["Witty, youthful, intelligent", "Eloquent, business wealth", "Great communicator, writer", "Learned, comfortable home", "Brilliant, clever intellect", "Analytical, defeats rivals", "Youthful, clever partner", "Occult research, long life", "Scholarly, philosophical", "Career in business & communication", "Gains via networking and trade", "Restless mind, foreign trade"],
  Jupiter: ["Wise, respected, blessed", "Wealthy, truthful speech", "Religious siblings, calm courage", "Happy home, vehicles, education", "Wise children, good counsel", "Overcomes enemies, service", "Noble, wise spouse", "Long life, occult wisdom", "Highly fortunate, spiritual", "Honourable career, advisor", "Abundant gains, good friends", "Charitable, spiritual, moksha"],
  Venus: ["Attractive, artistic, charming", "Sweet voice, wealth, fine food", "Artistic skills, loving siblings", "Luxurious home, vehicles", "Romantic, creative, talented", "Health issues, hidden enemies", "Beautiful, loving spouse", "Inheritance, secret pleasures", "Fortunate, devoted, generous", "Career in arts, luxury, beauty", "Gains via women, arts, luxury", "Bed pleasures, foreign comforts"],
  Saturn: ["Serious, disciplined, delays", "Frugal, slow wealth growth", "Persevering, brave, long life", "Detached from home, old property", "Delayed children, deep thinker", "Defeats enemies, hard worker", "Mature or delayed marriage", "Long life, chronic issues", "Traditional, delayed fortune", "Slow but lasting career rise", "Steady gains, elder friends", "Isolation, expenses, foreign lands"],
  Rahu: ["Magnetic, unconventional, restless", "Unusual speech, fluctuating wealth", "Bold, fearless, media success", "Unsettled home, foreign residence", "Unusual intellect, speculation", "Conquers enemies, clever", "Unconventional or foreign spouse", "Sudden events, occult power", "Unorthodox beliefs, foreign guru", "Ambitious, sudden career rise", "Huge gains, powerful network", "Foreign travel, hidden expenses"],
  Ketu: ["Spiritual, mysterious, intuitive", "Blunt speech, family detachment", "Courageous, spiritual efforts", "Detached from comforts, restless", "Intuitive intellect, past-life merit", "Victory over enemies, healing", "Detached or spiritual partner", "Occult mastery, sudden changes", "Unorthodox spirituality", "Unusual career, sudden shifts", "Gains through spirituality", "Moksha, liberation, foreign lands"],
};

export const IN_SIGN: Record<PlanetId, string[]> = {
  Sun: ["Exalted hero, natural leader", "Steady, wealth-minded", "Learned, communicative", "Emotional, home-loving", "Royal, commanding", "Analytical, modest", "Debilitated, diplomatic", "Intense, secretive", "Principled and wise", "Disciplined worker", "Humanitarian, detached", "Spiritual, compassionate"],
  Moon: ["Impulsive, brave mind", "Exalted, calm and content", "Witty, versatile mind", "Deeply caring, nurturing", "Proud, generous heart", "Practical, analytical mind", "Balanced, charming mind", "Debilitated, intense feelings", "Optimistic, philosophical", "Practical, reserved", "Humanitarian thinker", "Dreamy, compassionate"],
  Mars: ["Warrior in own sign", "Sensual, determined", "Argumentative, clever", "Debilitated, emotional anger", "Bold, commanding", "Precise, technical", "Passionate, diplomatic", "Secretive strategist", "Righteous fighter", "Exalted, disciplined achiever", "Revolutionary", "Idealistic, spiritual warrior"],
  Mercury: ["Quick, impulsive thinker", "Practical, business mind", "Brilliant communicator", "Emotional intellect", "Proud, creative speaker", "Exalted analyst", "Balanced negotiator", "Investigative mind", "Philosophical thinker", "Practical planner", "Innovative, scientific", "Debilitated, intuitive mind"],
  Jupiter: ["Dynamic teacher", "Wealthy, comfortable", "Scholarly, many interests", "Exalted, highly virtuous", "Noble leader", "Practical wisdom", "Just and fair", "Deep occult wisdom", "Guru in own sign", "Debilitated, practical", "Humanitarian sage", "Spiritual master"],
  Venus: ["Passionate lover", "Luxurious, artistic", "Charming, flirtatious", "Emotional romantic", "Glamorous, proud", "Debilitated, critical in love", "Refined, artistic", "Intense passions", "Idealistic lover", "Loyal, practical love", "Unconventional love", "Exalted, divine love"],
  Saturn: ["Debilitated, frustrated drive", "Patient wealth builder", "Serious thinker", "Emotional burdens", "Conflict with authority", "Methodical worker", "Exalted, just ruler", "Deep endurance", "Principled, orthodox", "Disciplined achiever", "Humanitarian reformer", "Spiritual discipline"],
  Rahu: ["Aggressive ambition", "Exalted, material desires", "Clever manipulator", "Emotional obsession", "Craves fame", "Analytical obsession", "Diplomatic ambition", "Secretive power", "Unorthodox beliefs", "Political ambition", "Innovative, tech-savvy", "Spiritual illusions"],
  Ketu: ["Detached warrior", "Detached from wealth", "Scattered intellect", "Emotional detachment", "Detached from ego", "Perfectionist healer", "Detached in relationships", "Exalted, occult mastery", "Spiritual seeker", "Detached from status", "Humanitarian mystic", "Moksha seeker"],
};
