"use client";

import Link from "next/link";
import { useState, type ReactNode } from "react";
import { PLANET_INFO } from "@/lib/astro/data";
import type { KaalSarpReport, MangalReport, SadeSatiReport } from "@/lib/dedicated-doshas/report";
import { RemedyList } from "@/components/chart/RemedyList";

type Report = KaalSarpReport | MangalReport | SadeSatiReport;
const fmt=(iso:string)=>new Date(iso).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric",timeZone:"UTC"});
function Tile({label,children}:{label:string;children:ReactNode}){return <div className="rounded-xl border border-white/10 bg-slate-950/30 p-3"><p className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">{label}</p><div className="mt-1 text-sm font-semibold text-slate-100">{children}</div></div>}
function Shell({title,sub,icon,children,report,chartSlug,newHref}:{title:string;sub:string;icon:string;children:ReactNode;report:Report;chartSlug:string;newHref:string}){const[copied,setCopied]=useState(false);const[failed,setFailed]=useState(false);const share=async()=>{try{await navigator.clipboard.writeText(location.href);setCopied(true);setTimeout(()=>setCopied(false),2500)}catch{setFailed(true)}};return <div><header className="card relative mb-6 overflow-hidden p-6 sm:p-8"><div className="pointer-events-none absolute -right-20 -top-20 h-56 w-56 rounded-full bg-violet-500/10 blur-3xl"/><p className="label-caps !text-amber-300">Saved dedicated report</p><h1 className="mt-2 font-serif text-4xl font-semibold text-slate-100 sm:text-5xl">{icon} {title}</h1><p className="mt-2 text-sm text-slate-400">{report.summary.name} · {report.summary.date} · {report.summary.time} · {report.summary.place}</p><p className="mt-2 max-w-3xl text-sm text-slate-300">{sub}</p><div className="mt-4 flex flex-wrap gap-3"><button type="button" onClick={share} className="rounded-full border border-slate-600 px-4 py-2 text-sm text-slate-300 hover:border-amber-400">{copied?"Link copied ✓":"Share this report"}</button><Link href={newHref} className="rounded-full border border-amber-400/40 px-4 py-2 text-sm text-amber-200 hover:bg-amber-400/10">New chart</Link><Link href={`/chart/${chartSlug}`} className="rounded-full border border-violet-400/40 px-4 py-2 text-sm text-violet-200">Full horoscope</Link></div>{failed&&<p className="mt-2 text-xs text-amber-200">Copy this page’s address from your browser to share it.</p>}</header>{children}</div>}

export function KaalSarpView({report:r,chartSlug}:{report:KaalSarpReport;chartSlug:string}){
  const result=r.present?`${r.typeName} Kaal Sarp is present`:r.partial?"Partial Kaal Sarp pattern":"No Kaal Sarp Dosha";
  const color=r.present?"#fb7185":r.partial?"#fbbf24":"#34d399";
  return <Shell title="Kaal Sarp Analysis" sub={r.sharedResult.details} icon="🐍" report={r} chartSlug={chartSlug} newHref="/calculators/kaal-sarp">
    <div className="space-y-5"><section className="card p-6"><p className="label-caps" style={{color}}>Result</p><h2 className="mt-1 font-serif text-3xl font-semibold" style={{color}}>{result}</h2><p className="mt-2 text-sm text-slate-300">{r.enclosedCount} of 7 classical planets lie on the more occupied semicircle. {r.direction}.</p><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Tile label="Type">{r.typeName} ({r.typeNumber})</Tile><Tile label="Rahu">{r.axis.rahu} · {r.axis.rahuDegree}</Tile><Tile label="Ketu">{r.axis.ketu} · {r.axis.ketuDegree}</Tile><Tile label="Outside axis">{r.outside.join(", ")||"None"}</Tile></div></section>
    <section className="card p-5"><h2 className="font-serif text-2xl font-semibold text-amber-200">Planet order from Rahu</h2><div className="scroll-thin mt-3 overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-800/50"><tr>{["Planet","Offset","Semicircle","Sign / House","Node distance"].map(h=><th key={h} className="p-3 text-left text-xs text-slate-400">{h}</th>)}</tr></thead><tbody>{r.sequence.map(p=><tr key={p.id} className="border-t border-slate-700/40"><td className="p-3 font-bold" style={{color:PLANET_INFO[p.id].color}}>{p.id}</td><td className="p-3 text-slate-300">{p.offsetFromRahu.toFixed(2)}°</td><td className="p-3 text-slate-400">{p.side}</td><td className="p-3 text-slate-300">{p.sign} · H{p.house}</td><td className="p-3 text-slate-400">{p.distanceToNearestNode.toFixed(2)}°</td></tr>)}</tbody></table></div></section>
    <div className="grid gap-4 md:grid-cols-2"><section className="card p-5"><h2 className="font-serif text-xl font-semibold text-amber-200">Traditional areas</h2><ul className="mt-2 list-disc pl-5 text-sm text-slate-300">{r.affectedAreas.map(x=><li key={x}>{x}</li>)}</ul></section><section className="card p-5"><h2 className="font-serif text-xl font-semibold text-emerald-300">Supportive factors</h2>{r.supports.length?<ul className="mt-2 list-disc pl-5 text-sm text-slate-300">{r.supports.map(x=><li key={x}>{x}</li>)}</ul>:<p className="mt-2 text-sm text-slate-400">No specific mitigation factor was found by this limited checklist. This does not make the result inevitable.</p>}</section></div>
    {r.remedies.length>0&&<section className="card p-5"><h2 className="mb-3 font-serif text-xl font-semibold text-teal-300">Optional remedies</h2><RemedyList remedies={r.remedies}/></section>}
    <Method notes={r.notes} method={r.method} version={r.version}/></div>
  </Shell>;
}

export function MangalView({report:r,chartSlug}:{report:MangalReport;chartSlug:string}){
  const color=r.present?"#fb7185":r.severity!=="None"?"#fbbf24":"#34d399";
  return <Shell title="Kuja / Mangal Dosha" sub={r.sharedResult.details} icon="♂" report={r} chartSlug={chartSlug} newHref="/calculators/mangal-dosha">
    <div className="space-y-5"><section className="card p-6"><p className="label-caps" style={{color}}>Result</p><h2 className="mt-1 font-serif text-3xl font-semibold" style={{color}}>{r.present?`${r.severity} Mangal Dosha`:r.severity!=="None"?"Placement present, but reduced / cancelled":"No Mangal Dosha"}</h2><p className="mt-2 text-sm text-slate-400">Visual intensity {r.score}/100 — based on reference hits, Mars strength and cancellations; not a classical point score.</p><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Tile label="Mars">{r.mars.sign} · H{r.mars.house}</Tile><Tile label="Dignity">{r.mars.dignity}</Tile><Tile label="Strength">{r.mars.strength}/100</Tile><Tile label="D9 Mars">{r.mars.navamsaSign} · H{r.mars.navamsaHouse}</Tile></div></section>
    <section className="grid gap-4 md:grid-cols-3">{r.references.map(x=><div key={x.reference} className={`rounded-2xl border p-5 ${x.manglik?"border-rose-500/35 bg-rose-500/5":"border-emerald-500/25 bg-emerald-500/5"}`}><p className="label-caps">From {x.reference}</p><p className={`mt-1 text-2xl font-bold ${x.manglik?"text-rose-300":"text-emerald-300"}`}>House {x.house}</p><p className="mt-2 text-sm text-slate-300">{x.theme}</p></div>)}</section>
    {r.cancellations.length>0&&<section className="rounded-2xl border border-emerald-500/30 bg-emerald-500/5 p-5"><h2 className="font-serif text-xl font-semibold text-emerald-300">Cancellations / reductions</h2><ul className="mt-2 list-disc pl-5 text-sm text-slate-300">{r.cancellations.map(x=><li key={x}>{x}</li>)}</ul></section>}
    <section className="card p-5"><h2 className="font-serif text-2xl font-semibold text-amber-200">Marriage context beyond Mars</h2><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4"><Tile label="7th sign / lord">{r.marriage.seventhSign} · {r.marriage.seventhLord}</Tile><Tile label="7th lord house">H{r.marriage.lordHouse}</Tile><Tile label="Planets in 7th">{r.marriage.planetsInSeventh.join(", ")||"Empty"}</Tile><Tile label="Venus">H{r.marriage.venusHouse} · {r.marriage.venusDignity}</Tile><Tile label="Jupiter house">H{r.marriage.jupiterHouse}</Tile><Tile label="D9 7th lord">{r.marriage.navamsaSeventhLord} · H{r.marriage.navamsaLordHouse}</Tile><Tile label="Mars conjunctions">{r.mars.conjunctions.join(", ")||"None"}</Tile><Tile label="Mars aspects">H{r.mars.aspects.join(", H")}</Tile></div></section>
    {r.remedies.length>0&&<section className="card p-5"><h2 className="mb-3 font-serif text-xl font-semibold text-teal-300">Optional remedies</h2><RemedyList remedies={r.remedies}/></section>}
    <Method notes={r.notes} method={r.method} version={r.version}/></div>
  </Shell>;
}

export function SadeSatiView({report:r,chartSlug}:{report:SadeSatiReport;chartSlug:string}){
  const color=r.active?"#fb7185":r.dhaiya.active?"#fbbf24":"#34d399";
  return <Shell title="Sade Sati" sub={r.summaryText} icon="🪐" report={r} chartSlug={chartSlug} newHref="/calculators/sade-sati">
    <div className="space-y-5"><section className="card p-6"><p className="label-caps" style={{color}}>Current status</p><h2 className="mt-1 font-serif text-3xl font-semibold" style={{color}}>{r.active?"Sade Sati is running":r.dhaiya.active?"Sade Sati is not running · Dhaiya is active":"Sade Sati is not running"}</h2><p className="mt-2 text-sm text-slate-300">{r.summaryText}</p><p className="mt-1 text-sm text-slate-400">{r.dhaiya.summary}</p><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Tile label="Transit Saturn">{r.currentSaturn.sign} · {r.currentSaturn.degree}</Tile><Tile label="From Moon">H{r.currentSaturn.houseFromMoon}</Tile><Tile label="From Lagna">H{r.currentSaturn.houseFromLagna}</Tile><Tile label="Running dasha">{r.runningDasha.chain.join(" → ")||"—"}</Tile></div></section>
    <section><h2 className="mb-3 font-serif text-2xl font-semibold text-amber-200">Phase timeline</h2><ol className="space-y-3">{r.phases.map(p=><li key={`${p.phase}-${p.start}`} className={`rounded-2xl border p-4 ${p.status==="current"?"border-amber-400/50 bg-amber-400/10":p.status==="past"?"border-slate-700 bg-slate-900/20 opacity-80":"border-sky-500/25 bg-sky-500/5"}`}><div className="flex flex-wrap justify-between gap-2"><p className="font-semibold text-slate-100">{p.phase} · {p.sign}</p><span className="text-xs uppercase text-slate-400">{p.status}</span></div><p className="mt-1 text-sm text-slate-400">{fmt(p.start)} → {fmt(p.end)}</p><p className="mt-2 text-sm text-slate-300">{p.note}</p></li>)}</ol></section>
    <section className="card p-5"><h2 className="font-serif text-2xl font-semibold text-amber-200">Your natal Saturn</h2><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4"><Tile label="Sign">{r.natalSaturn.sign} · {r.natalSaturn.degree}</Tile><Tile label="House">H{r.natalSaturn.house}</Tile><Tile label="Dignity">{r.natalSaturn.dignity}</Tile><Tile label="Strength">{r.natalSaturn.strength}/100{r.natalSaturn.retro?" · Retrograde":""}</Tile></div>{r.runningDasha.saturnInChain&&<p className="mt-3 rounded-xl bg-amber-500/10 p-3 text-sm text-amber-200">Saturn also rules one of your running Dasha levels, so its themes may feel more prominent.</p>}</section>
    {r.remedies.length>0&&<section className="card p-5"><h2 className="mb-3 font-serif text-xl font-semibold text-teal-300">Safe traditional practices</h2><RemedyList remedies={r.remedies}/></section>}
    <Method notes={r.notes} method={r.method} version={r.version}/></div>
  </Shell>;
}

function Method({notes,method,version}:{notes:string[];method:string;version:string}){return <section className="card p-5"><h2 className="font-serif text-2xl font-semibold text-amber-200">Method & limitations</h2><p className="mt-1 text-sm text-slate-400">{method}</p><ul className="mt-4 list-disc space-y-3 pl-5 text-sm text-slate-300">{notes.map(n=><li key={n}>{n}</li>)}</ul><p className="mt-4 text-xs text-slate-500">Engine version {version}</p></section>}
