"use client";

import Link from "next/link";
import { useState, type ReactNode } from "react";
import type { ChartData } from "@/lib/astro/calc";
import { fmtDeg } from "@/lib/astro/calc";
import { avakhada, planet } from "@/lib/astro/analysis";
import { NAKSHATRAS, PLANET_INFO, SIGNS } from "@/lib/astro/data";
import type { MatchCheck, MatchResult } from "@/lib/matching/report";
import { GANA_MATRIX, MATCHING_SOURCES, VASHYA_MATRIX, VASHYA_NAMES, YONI_MATRIX, YONI_NAMES } from "@/lib/matching/rules";
import ChartSVG from "@/components/chart/ChartSVG";
import HouseModal, { vargaAsc, vargaSign, type Varga } from "@/components/chart/HouseModal";
import ClickHint from "@/components/chart/ClickHint";
import { RemedyList } from "@/components/chart/RemedyList";

const TABS = [
  ["summary", "✦", "Summary"], ["score", "📊", "36-point breakdown"], ["mangal", "♂", "Manglik & flags"],
  ["charts", "🪐", "Both charts"], ["marriage", "💞", "Marriage & timing"], ["remedies", "🪔", "Guidance & remedies"], ["method", "📖", "Method"],
] as const;
type Tab = (typeof TABS)[number][0];
const date = (value: number | string) => new Date(value).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" });
const STATUS = { clear: "border-emerald-500/30 bg-emerald-500/5 text-emerald-300", review: "border-rose-500/30 bg-rose-500/5 text-rose-300", mitigated: "border-amber-500/30 bg-amber-500/5 text-amber-200" };

function Heading({ title, sub }: { title: string; sub?: string }) { return <div className="mb-4"><h2 className="font-serif text-3xl font-semibold text-slate-100">{title}</h2>{sub && <p className="mt-1 text-sm leading-relaxed text-slate-400">{sub}</p>}</div>; }
function Tile({ label, children }: { label: string; children: ReactNode }) { return <div className="rounded-xl border border-white/10 bg-slate-950/30 p-3"><p className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold text-slate-100">{children}</p></div>; }

function Profile({ c, chartSlug, accent }: { c: ChartData; chartSlug: string; accent: string }) {
  const a = avakhada(c), m = planet(c, "Moon");
  return (
    <section className="card min-w-0 p-5">
      <div className="mb-4"><h3 className="font-serif text-2xl font-semibold" style={{ color: accent }}>{c.input.name}</h3><p className="mt-1 text-xs text-slate-400">{date(c.input.date)} · {c.input.time.slice(0, 5)} (24 hr)<br />{c.input.place}</p></div>
      <div className="grid grid-cols-2 gap-2">
        <Tile label="Lagna">{a.lagna.sa} · {a.lagna.en}</Tile><Tile label="Moon sign">{a.rashi.sa} · {a.rashi.en}</Tile>
        <Tile label="Star & Pada">{a.nakshatra.name} · {a.pada}</Tile><Tile label="Moon degree">{fmtDeg(m.deg)}</Tile>
        <Tile label="Gana">{a.gana}</Tile><Tile label="Nadi">{a.nadi}</Tile><Tile label="Yoni">{a.yoni}</Tile><Tile label="Varna">{a.varna}</Tile>
      </div>
      <p className="mt-3 text-xs text-slate-500">{c.input.lat.toFixed(4)}°, {c.input.lon.toFixed(4)}° · {c.input.tz}</p>
      <Link href={`/chart/${chartSlug}`} className="mt-3 inline-flex items-center gap-2 text-sm font-semibold text-amber-300 hover:underline">View full individual horoscope →</Link>
    </section>
  );
}

function CheckCard({ check }: { check: MatchCheck }) {
  return <section className={`rounded-2xl border p-5 ${STATUS[check.status]}`}><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-serif text-xl font-semibold">{check.title}</h3><span className="rounded-full bg-black/20 px-2.5 py-1 text-[11px] font-semibold">{check.status === "clear" ? "Clear in this method" : check.status === "mitigated" ? "Possible mitigation" : "Review"}</span></div><p className="mt-2 text-sm leading-relaxed text-slate-200">{check.summary}</p><ul className="mt-2 list-disc space-y-1 pl-4 text-xs text-slate-400">{check.evidence.map((e) => <li key={e}>{e}</li>)}</ul></section>;
}

function Matrix({ title, names, values }: { title: string; names: string[]; values: number[][] }) {
  return <details className="card p-4"><summary className="cursor-pointer font-semibold text-amber-200">{title} — click to see the table</summary><div className="scroll-thin mt-3 overflow-x-auto"><table className="w-full border-collapse text-xs"><thead><tr><th className="border border-slate-700 p-2 text-left">Second ↓ / First →</th>{names.map((n) => <th key={n} className="border border-slate-700 p-2">{n}</th>)}</tr></thead><tbody>{values.map((row, i) => <tr key={names[i]}><th className="border border-slate-700 p-2 text-left font-medium text-slate-300">{names[i]}</th>{row.map((v, j) => <td key={j} className="border border-slate-700 p-2 text-center text-slate-400">{v}</td>)}</tr>)}</tbody></table></div></details>;
}

export default function MatchingReport({ result: r, first, second, firstChartSlug, secondChartSlug }: { result: MatchResult; first: ChartData; second: ChartData; firstChartSlug: string; secondChartSlug: string }) {
  const [tab, setTab] = useState<Tab>("summary");
  const [copied, setCopied] = useState(false);
  const [shareError, setShareError] = useState(false);
  const [style, setStyle] = useState<"north" | "south">(first.input.style);
  const [varga, setVarga] = useState<Varga>("D1");
  const [house, setHouse] = useState<{ person: 0 | 1; house: number } | null>(null);
  const scoreColor = r.total >= 25 ? "#34d399" : r.total >= 18 ? "#fbbf24" : "#fb7185";
  const profiles = [{ c: first, slug: firstChartSlug, color: "#fbbf24" }, { c: second, slug: secondChartSlug, color: "#f9a8d4" }];
  const circumference = 2 * Math.PI * 66;
  const share = async () => {
    try { await navigator.clipboard.writeText(window.location.href); setCopied(true); setTimeout(() => setCopied(false), 2500); }
    catch { setShareError(true); }
  };

  let content: ReactNode;
  if (tab === "summary") {
    content = <div className="space-y-6">
      <div className="card grid items-center gap-6 p-6 sm:grid-cols-[200px_1fr]">
        <div className="relative mx-auto h-44 w-44"><svg viewBox="0 0 160 160" className="h-full w-full -rotate-90"><circle cx="80" cy="80" r="66" stroke="#293044" strokeWidth="9" fill="none" /><circle cx="80" cy="80" r="66" stroke={scoreColor} strokeWidth="9" fill="none" strokeLinecap="round" strokeDasharray={`${r.total / 36 * circumference} ${circumference}`} /></svg><div className="absolute inset-0 flex flex-col items-center justify-center"><span className="text-5xl font-bold" style={{ color: scoreColor }}>{r.total}</span><span className="mt-1 text-sm text-slate-400">out of 36 points</span></div></div>
        <div><p className="label-caps !text-amber-300">Traditional Guna Milan</p><h2 className="mt-1 font-serif text-3xl font-semibold text-slate-100">{r.band}</h2><p className="mt-3 text-sm leading-relaxed text-slate-300">{r.summary}</p><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={() => setTab("score")} className="rounded-full bg-amber-400 px-4 py-2 text-sm font-semibold text-slate-950">Explain every point →</button><button type="button" onClick={() => setTab("mangal")} className="rounded-full border border-slate-600 px-4 py-2 text-sm text-slate-300">Review flags →</button></div><p className="mt-3 text-xs text-slate-500">{r.percentage}% of the available points—not a success probability. Cancellation notes do not change this raw total.</p></div>
      </div>
      {r.timeWarnings.length > 0 && <div className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm text-amber-200">{r.timeWarnings.map((w) => <p key={w}>{w}</p>)}</div>}
      <div className="grid gap-4 lg:grid-cols-2">{profiles.map((p) => <Profile key={p.slug} c={p.c} chartSlug={p.slug} accent={p.color} />)}</div>
      <div className="grid gap-4 md:grid-cols-2"><section className="rounded-2xl border border-emerald-500/25 bg-emerald-500/5 p-5"><h3 className="font-semibold text-emerald-300">Supportive factors</h3><ul className="mt-2 list-disc space-y-2 pl-5 text-sm text-slate-300">{r.strengths.length ? r.strengths.map((s) => <li key={s}>{s}</li>) : <li>No factor reaches 75% of its available points.</li>}</ul></section><section className="rounded-2xl border border-amber-500/25 bg-amber-500/5 p-5"><h3 className="font-semibold text-amber-200">Read before interpreting the score</h3><ul className="mt-2 list-disc space-y-2 pl-5 text-sm text-slate-300">{r.considerations.length ? r.considerations.map((s) => <li key={s}>{s}</li>) : <li>No unresolved major flags in the reviewed factors; personal compatibility and a full-chart consultation still matter.</li>}</ul></section></div>
      <button type="button" onClick={() => setTab("remedies")} className="text-sm font-semibold text-amber-300 hover:underline">See personalised guidance & remedies →</button>
    </div>;
  } else if (tab === "score") {
    content = <div><Heading title="Where every point comes from" sub="Click each heading to expand its values, formula, calculation and practical guidance. The eight maximum weights add up to 36." /><div className="space-y-3">{r.kootas.map((k) => <details key={k.key} className="card overflow-hidden"><summary className="flex cursor-pointer list-none items-center gap-3 p-4 sm:p-5"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-violet-500/20 text-sm font-bold text-violet-200">{k.max}</span><div className="min-w-0 flex-1"><h3 className="font-semibold text-slate-100">{k.name}</h3><p className="text-xs text-slate-500">{k.topic}</p></div><span className={`rounded-full px-3 py-1 text-sm font-bold ${k.score / k.max >= .75 ? "bg-emerald-400/15 text-emerald-300" : k.score === 0 ? "bg-rose-400/15 text-rose-300" : "bg-amber-400/15 text-amber-200"}`}>{k.score} / {k.max}</span><span className="text-slate-400">⌄</span></summary><div className="space-y-4 border-t border-slate-700/40 p-5"><div className="grid grid-cols-2 gap-3"><Tile label={first.input.name}>{k.firstValue}</Tile><Tile label={second.input.name}>{k.secondValue}</Tile></div><div><p className="label-caps !text-violet-300">Scoring rule</p><p className="mt-1 text-sm text-slate-300">{k.rule}</p></div><ul className="list-disc space-y-1 pl-5 text-sm text-slate-400">{k.evidence.map((e) => <li key={e}>{e}</li>)}</ul><p className="text-sm font-medium text-slate-200">{k.interpretation}</p><p className="rounded-xl bg-slate-950/40 p-3 text-sm text-slate-400">{k.advice}</p></div></details>)}</div><p className="mt-4 text-right text-lg font-semibold text-amber-200">Raw total: {r.total} / 36</p></div>;
  } else if (tab === "mangal") {
    content = <div className="space-y-5"><Heading title="Manglik balance & compatibility flags" sub="These checks add context, not extra points. They use the same Mangal placements and cancellation rules as each main horoscope." /><div className="card p-5"><p className="font-semibold text-amber-200">{r.manglik.status === "balanced" ? "Balanced / no uncancelled mismatch" : r.manglik.status === "different" ? "Different Mangal flags" : "Both charts need Mangal review"}</p><p className="mt-2 text-sm leading-relaxed text-slate-300">{r.manglik.summary}</p></div><div className="grid gap-4 lg:grid-cols-2">{profiles.map((p, i) => { const d = i === 0 ? r.manglik.first : r.manglik.second; const hs = i === 0 ? r.manglik.firstHouses : r.manglik.secondHouses; return <section key={p.slug} className="card p-5"><h3 className="font-serif text-2xl font-semibold" style={{ color: p.color }}>{p.c.input.name}</h3><p className="mt-2 font-semibold text-slate-100">{d.present ? `Active — ${d.severity}` : d.severity === "None" ? "No Mangal flag" : `${d.severity} — reduced / cancelled`}</p><div className="mt-3 grid grid-cols-3 gap-2">{hs.map((h, j) => <Tile key={j} label={["From Lagna", "From Moon", "From Venus"][j]}>House {h}</Tile>)}</div><p className="mt-3 text-sm leading-relaxed text-slate-300">{d.details}</p>{d.severity !== "None" && <details className="mt-3"><summary className="cursor-pointer text-sm font-semibold text-amber-300">Click for individual Mars remedies</summary><div className="mt-3"><RemedyList remedies={d.remedies} compact /></div></details>}</section>; })}</div><div className="grid gap-4 lg:grid-cols-3">{r.checks.map((c) => <CheckCard key={c.key} check={c} />)}</div></div>;
  } else if (tab === "charts") {
    content = <div><Heading title="Both horoscopes, calculated together" sub="D1 and D9 positions come from the existing birth-chart engine. No sample or random placements are used." /><ClickHint title="Click a house for details">Explore each sign, house and planet in the same popup as the main horoscope.</ClickHint><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex rounded-xl border border-slate-600 p-1">{(["D1", "D9"] as const).map((v) => <button type="button" key={v} onClick={() => setVarga(v)} className={`rounded-lg px-4 py-2 text-sm ${varga === v ? "bg-violet-500 font-semibold text-white" : "text-slate-400"}`}>{v === "D1" ? "D1 · Rashi" : "D9 · Navamsa"}</button>)}</div><div className="flex rounded-xl border border-slate-600 p-1">{(["north", "south"] as const).map((s) => <button type="button" key={s} onClick={() => setStyle(s)} className={`rounded-lg px-3 py-2 text-sm ${style === s ? "bg-amber-400 font-semibold text-slate-950" : "text-slate-400"}`}>{s === "north" ? "North Indian" : "South Indian"}</button>)}</div></div><div className="grid gap-5 lg:grid-cols-2">{profiles.map((p, i) => <section className="card p-5" key={p.slug}><div className="mb-3 flex items-center justify-between gap-2"><h3 className="font-serif text-2xl font-semibold" style={{ color: p.color }}>{p.c.input.name}</h3><span className="text-xs text-slate-400">{varga} ascendant {SIGNS[vargaAsc(p.c, varga)].sa}</span></div><div className="mx-auto max-w-[460px]"><ChartSVG style={style} ascSign={vargaAsc(p.c, varga)} placements={p.c.planets.map((q) => ({ id: q.id, sign: vargaSign(q, varga), deg: q.deg, retro: q.retro }))} onHouseClick={(h) => setHouse({ person: i as 0 | 1, house: h })} showDegrees={varga === "D1"} /></div><Link href={`/chart/${p.slug}`} className="mt-3 block text-center text-sm font-semibold text-amber-300 hover:underline">All charts, planetary strengths & dashas →</Link></section>)}</div><div className="card scroll-thin mt-5 overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-800/50"><tr>{["Planet", `${first.input.name} · D1`, "Degree", "House", "D9", `${second.input.name} · D1`, "Degree", "House", "D9"].map((h, i) => <th key={i} className="whitespace-nowrap p-3 text-left text-xs font-semibold text-slate-400">{h}</th>)}</tr></thead><tbody>{first.planets.map((a, i) => { const b = second.planets[i]; return <tr key={a.id} className="border-t border-slate-700/40"><td className="p-3 font-bold" style={{ color: PLANET_INFO[a.id].color }}>{a.id}</td>{[SIGNS[a.sign].sa, fmtDeg(a.deg), a.house, SIGNS[a.d9].sa, SIGNS[b.sign].sa, fmtDeg(b.deg), b.house, SIGNS[b.d9].sa].map((v, j) => <td key={j} className="whitespace-nowrap p-3 text-slate-300">{v}</td>)}</tr>; })}</tbody></table></div></div>;
  } else if (tab === "marriage") {
    content = <div className="space-y-5"><Heading title="Marriage indicators beyond the Moon score" sub="The 7th house, its lord, Navamsa and dasha themes are evaluated using the existing individual horoscope logic." /><div className="grid gap-5 lg:grid-cols-2">{profiles.map((p, i) => { const m = i === 0 ? r.marriage.first : r.marriage.second; const d = i === 0 ? r.running.first : r.running.second; return <section className="card p-5" key={p.slug}><h3 className="font-serif text-2xl font-semibold" style={{ color: p.color }}>{p.c.input.name}</h3><div className="mt-3 grid grid-cols-2 gap-2"><Tile label="7th sign & lord">{m.seventhSign} · {m.seventhLord}</Tile><Tile label="7th lord placement">House {m.lordHouse}</Tile><Tile label="Planets in 7th">{m.planetsInSeventh.join(", ") || "Empty"}</Tile><Tile label="D9 Lagna">{m.navamsaLagna}</Tile><Tile label="D9 7th lord">{m.navamsaSeventhLord}</Tile><Tile label="D9 lord placement">House {m.navamsaLordHouse}</Tile></div><div className="mt-4 space-y-3 text-sm leading-relaxed text-slate-300">{m.paragraphs.map((t, j) => <p key={j}>{t}</p>)}</div><div className="mt-4 rounded-xl border border-violet-400/20 bg-violet-400/5 p-3"><p className="label-caps !text-violet-300">Dasha at calculation</p><p className="mt-1 font-semibold text-slate-200">{d.chain.join(" → ") || "Not available"}</p><p className="text-xs text-slate-400">{d.end ? `Pratyantar ends ${date(d.end)}. ` : ""}{d.themes}</p></div></section>; })}</div><section className="card p-5"><h3 className="font-serif text-2xl font-semibold text-amber-200">Overlapping relationship-significator periods</h3><p className="mt-2 text-xs text-slate-500">Next five years from the saved calculation date. These are periods when both Antardasha lords are Venus, Jupiter or their own 7th lord—not guaranteed marriage dates or auspicious wedding muhurta.</p>{r.commonWindows.length ? <ul className="mt-3 space-y-2">{r.commonWindows.map((w) => <li key={`${w.start}-${w.end}`} className="rounded-xl bg-slate-950/40 p-3 text-sm"><b className="text-slate-100">{date(w.start)} → {date(w.end)}</b><p className="mt-1 text-xs text-slate-400">{first.input.name}: {w.first} · {second.input.name}: {w.second}</p></li>)}</ul> : <p className="mt-3 text-sm text-slate-400">No overlapping periods under this simple filter were found in the next five years. That is not a prediction that marriage cannot happen.</p>}</section></div>;
  } else if (tab === "remedies") {
    content = <div className="space-y-5"><Heading title="Practical guidance & optional traditional remedies" sub="Start with honest communication. Practices below are voluntary; no remedy or expensive stone guarantees a relationship outcome." /><section className="card p-5"><RemedyList remedies={r.remedies} /></section>{r.checks.filter((c) => c.status !== "clear").map((c) => <section key={c.key} className="card p-5"><h3 className="mb-3 font-serif text-xl font-semibold text-amber-200">{c.title}</h3><RemedyList remedies={c.remedies} /></section>)}</div>;
  } else {
    content = <div className="space-y-4"><Heading title="Transparent method, settings & limitations" sub={r.method} /><section className="card p-5"><ul className="list-disc space-y-3 pl-5 text-sm leading-relaxed text-slate-300">{r.notes.map((n) => <li key={n}>{n}</li>)}</ul><p className="mt-4 text-xs text-slate-500">Engine version: {r.version} · calculation: {date(r.calculatedAt)}. Both birth inputs and calculated positions are saved with this report.</p></section><Matrix title="Vashya matrix" names={VASHYA_NAMES.map((x) => x.split(" (")[0])} values={VASHYA_MATRIX} /><Matrix title="Gana matrix" names={["Deva", "Manushya", "Rakshasa"]} values={GANA_MATRIX} /><Matrix title="Yoni matrix" names={YONI_NAMES} values={YONI_MATRIX} /><section className="card p-5"><h3 className="mb-2 font-semibold text-slate-100">Scoring references</h3><ul className="space-y-2 text-sm">{MATCHING_SOURCES.map((s) => <li key={s.url}><a href={s.url} target="_blank" rel="noopener noreferrer" className="text-amber-300 hover:underline">{s.title} ↗</a></li>)}</ul></section></div>;
  }

  return (
    <div>
      <header className="card relative mb-6 overflow-hidden p-6 sm:p-8"><div className="pointer-events-none absolute -right-20 -top-20 h-56 w-56 rounded-full bg-pink-500/10 blur-3xl" /><p className="label-caps !text-amber-300">Saved marriage matching report</p><h1 className="mt-2 font-serif text-4xl font-semibold text-slate-100 sm:text-5xl">{first.input.name} <span className="text-pink-300">&</span> {second.input.name}</h1><p className="mt-2 text-sm text-slate-400">Ashtakoota · Lahiri sidereal · {date(r.calculatedAt)}</p><div className="mt-4 flex flex-wrap gap-3"><span className="rounded-full px-4 py-2 text-sm font-bold" style={{ background: `${scoreColor}20`, color: scoreColor }}>{r.total}/36 points</span><button type="button" onClick={share} className="rounded-full border border-slate-600 px-4 py-2 text-sm text-slate-300 hover:border-amber-400">{copied ? "Link copied ✓" : "Share this result"}</button><Link href="/calculators/marriage-matching" className="rounded-full border border-amber-400/40 px-4 py-2 text-sm text-amber-200 hover:bg-amber-400/10">New comparison</Link></div>{shareError && <p className="mt-2 text-xs text-amber-200">Copy this page’s address from your browser to share the result.</p>}<p className="mt-3 text-xs text-slate-500">Share only with consent: this link includes both people’s birth details.</p></header>
      <nav aria-label="Matching report sections" className="scroll-thin mb-6 flex gap-2 overflow-x-auto pb-2">{TABS.map(([key, icon, text]) => <button type="button" key={key} onClick={() => setTab(key)} aria-pressed={tab === key} className={`shrink-0 rounded-xl border px-4 py-2.5 text-sm transition ${tab === key ? "border-amber-400/60 bg-amber-400/15 font-semibold text-amber-200" : "border-slate-700 bg-slate-900/30 text-slate-400 hover:text-slate-200"}`}>{icon} {text}</button>)}</nav>
      <div key={tab} className="animate-pop">{content}</div>
      {house && <HouseModal c={house.person === 0 ? first : second} varga={varga} house={house.house} onClose={() => setHouse(null)} />}
    </div>
  );
}
