"use client";

import Link from "next/link";
import { useState, type ReactNode } from "react";
import { PLANET_INFO } from "@/lib/astro/data";
import type { NakshatraReport } from "@/lib/nakshatra/report";
import { RemedyList } from "@/components/chart/RemedyList";

const TABS = [["summary", "✦", "Summary"], ["star", "⭐", "Nakshatra & padas"], ["rashi", "☽", "Moon sign"], ["avakhada", "🪷", "Avakhada & Panchang"], ["tara", "🔯", "Tara & lucky factors"], ["remedies", "🪔", "Guidance"], ["method", "📖", "Method"]] as const;
type Tab = (typeof TABS)[number][0];

function Tile({ label, children, accent }: { label: string; children: ReactNode; accent?: string }) {
  return <div className="rounded-xl border border-white/10 bg-slate-950/30 p-3"><p className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold" style={{ color: accent ?? "#f1f5f9" }}>{children}</p></div>;
}
function PairGrid({ values }: { values: Record<string, string | number> }) {
  return <div className="grid gap-2 sm:grid-cols-2">{Object.entries(values).map(([k, v]) => <Tile key={k} label={k.replace(/([A-Z])/g, " $1").replace(/^./, (x) => x.toUpperCase())}>{String(v)}</Tile>)}</div>;
}

export default function NakshatraReportView({ report: r, chartSlug }: { report: NakshatraReport; chartSlug: string }) {
  const [tab, setTab] = useState<Tab>("summary");
  const [copied, setCopied] = useState(false);
  const [shareFailed, setShareFailed] = useState(false);
  const share = async () => { try { await navigator.clipboard.writeText(window.location.href); setCopied(true); setTimeout(() => setCopied(false), 2500); } catch { setShareFailed(true); } };

  let content: ReactNode;
  if (tab === "summary") {
    content = <div className="space-y-6">
      <section className="card grid items-center gap-6 p-6 sm:grid-cols-[180px_1fr]">
        <div className="relative mx-auto flex h-40 w-40 items-center justify-center rounded-full border border-amber-400/30 bg-gradient-to-br from-amber-400/15 to-violet-500/15">
          <span className="glyph text-7xl text-amber-200">{r.rashi.glyph + "\uFE0E"}</span>
          <span className="absolute -bottom-2 rounded-full bg-[#11152d] px-4 py-1 text-xs font-semibold text-violet-200">Pada {r.moon.pada}</span>
        </div>
        <div>
          <p className="label-caps !text-amber-300">Janma Nakshatra</p>
          <h2 className="mt-1 font-serif text-4xl font-semibold text-slate-100">{r.moon.nakshatra}</h2>
          <p className="mt-1 text-xl text-violet-200">{r.rashi.sanskrit} ({r.rashi.english}) · {r.moon.degree}</p>
          <p className="mt-3 text-sm leading-relaxed text-slate-300">{r.nakshatra.traits}</p>
          <div className="mt-4 h-2 max-w-md overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-gradient-to-r from-amber-400 to-violet-500" style={{ width: `${r.moon.traversedPercent}%` }} /></div>
          <p className="mt-1 text-xs text-slate-500">Moon has traversed {r.moon.traversedPercent}% of {r.moon.nakshatra} · span {r.moon.startDegree} → {r.moon.endDegree}</p>
        </div>
      </section>
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
        <Tile label="Nakshatra lord" accent={PLANET_INFO[r.moon.lord].color}>{r.moon.lord}</Tile><Tile label="Deity">{r.nakshatra.deity}</Tile><Tile label="Birth syllable" accent="#f9a8d4">{r.nakshatra.birthSyllable}</Tile><Tile label="Pada Navamsa">{r.moon.padaNavamsa}</Tile>
        <Tile label="Gana">{r.nakshatra.gana}</Tile><Tile label="Yoni">{r.nakshatra.yoni} ({r.nakshatra.yoniGender})</Tile><Tile label="Nadi">{r.nakshatra.nadi}</Tile><Tile label="Symbol">{r.nakshatra.symbol}</Tile>
      </div>
      <section className="card p-5"><h2 className="font-serif text-2xl font-semibold text-amber-200">Your Moon&apos;s condition</h2><p className="mt-2 text-sm leading-relaxed text-slate-300">{r.moonCondition.summary}</p><div className="mt-3 grid gap-2 sm:grid-cols-3"><Tile label="House">{r.moonCondition.house}</Tile><Tile label="Moon dignity">{r.moonCondition.dignity}</Tile><Tile label="Phase">{r.moonCondition.waxing ? "Waxing (Shukla strength)" : "Waning (Krishna phase)"}</Tile></div></section>
      <section className="card p-5"><h2 className="mb-3 font-serif text-2xl font-semibold text-amber-200">Personalised interpretation</h2><div className="grid gap-3 md:grid-cols-2">{r.interpretations.map((p) => <div key={p.title} className="rounded-xl bg-slate-950/40 p-4"><h3 className="font-semibold text-violet-200">{p.title}</h3><p className="mt-1 text-sm leading-relaxed text-slate-300">{p.text}</p></div>)}</div></section>
      <section className="card p-5"><Link href={`/chart/${chartSlug}`} className="text-sm font-semibold text-amber-300 hover:underline">Open the complete horoscope for this birth chart →</Link></section>
    </div>;
  } else if (tab === "star") {
    content = <div className="space-y-5">
      <section className="card p-5"><h2 className="font-serif text-3xl font-semibold text-amber-200">{r.moon.nakshatra}</h2><p className="mt-1 text-sm text-slate-400">Lord {r.moon.lord} · deity {r.nakshatra.deity} · {r.nakshatra.nature}</p><p className="mt-3 text-sm leading-relaxed text-slate-300">{r.nakshatra.traits}</p><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{r.nakshatra.fourPadas.map((p) => <div key={p.pada} className={`rounded-xl border p-4 ${p.active ? "border-amber-400/50 bg-amber-400/10" : "border-slate-700/60 bg-slate-950/30"}`}><div className="flex items-center justify-between"><h3 className="font-semibold text-slate-100">Pada {p.pada}</h3>{p.active && <span className="rounded-full bg-amber-400 px-2 py-0.5 text-[10px] font-bold text-slate-950">YOUR PADA</span>}</div><p className="mt-2 text-sm text-pink-200">Syllable: {p.syllable}</p><p className="text-xs text-violet-200">Navamsa: {p.navamsa}</p><p className="mt-2 text-xs leading-relaxed text-slate-400">{p.focus}</p></div>)}</div></section>
      <div className="grid gap-4 md:grid-cols-2"><section className="rounded-2xl border border-emerald-500/30 bg-emerald-500/5 p-5"><h2 className="font-serif text-xl font-semibold text-emerald-300">Natural strengths</h2><div className="mt-3 flex flex-wrap gap-2">{r.nakshatra.strengths.map((s) => <span key={s} className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs text-emerald-100">{s}</span>)}</div></section><section className="rounded-2xl border border-rose-500/30 bg-rose-500/5 p-5"><h2 className="font-serif text-xl font-semibold text-rose-300">Watch for</h2><div className="mt-3 flex flex-wrap gap-2">{r.nakshatra.watchFor.map((s) => <span key={s} className="rounded-full bg-rose-400/10 px-3 py-1 text-xs text-rose-100">{s}</span>)}</div></section></div>
    </div>;
  } else if (tab === "rashi") {
    content = <div className="space-y-5"><section className="card relative overflow-hidden p-6"><div className="pointer-events-none absolute -right-8 -top-10 glyph text-[150px] text-violet-300/10">{r.rashi.glyph + "\uFE0E"}</div><p className="label-caps !text-violet-300">Chandra Rashi · Moon Sign</p><h2 className="mt-1 font-serif text-4xl font-semibold text-amber-200">{r.rashi.sanskrit} <span className="text-2xl text-slate-300">{r.rashi.english}</span></h2><p className="mt-3 max-w-3xl text-lg leading-relaxed text-slate-200">{r.rashi.archetype}</p><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4"><Tile label="Lord" accent={PLANET_INFO[r.rashi.lord].color}>{r.rashi.lord}</Tile><Tile label="Element">{r.rashi.element}</Tile><Tile label="Quality">{r.rashi.quality}</Tile><Tile label="Purushartha">{r.rashi.purushartha}</Tile><Tile label="Guna">{r.rashi.guna}</Tile><Tile label="Gender">{r.rashi.gender}</Tile><Tile label="Direction">{r.rashi.direction}</Tile><Tile label="Body">{r.rashi.body}</Tile></div></section><div className="grid gap-4 md:grid-cols-2"><section className="rounded-2xl border border-emerald-500/30 bg-emerald-500/5 p-5"><h2 className="font-serif text-xl font-semibold text-emerald-300">Strengths of {r.rashi.english}</h2><ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-slate-300">{r.rashi.strengths.map((s) => <li key={s}>{s}</li>)}</ul></section><section className="rounded-2xl border border-rose-500/30 bg-rose-500/5 p-5"><h2 className="font-serif text-xl font-semibold text-rose-300">Challenges to balance</h2><ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-slate-300">{r.rashi.watchFor.map((s) => <li key={s}>{s}</li>)}</ul></section></div></div>;
  } else if (tab === "avakhada") {
    content = <div className="space-y-5"><section className="card p-5"><h2 className="mb-3 font-serif text-2xl font-semibold text-amber-200">Avakhada Chakra</h2><PairGrid values={r.avakhada} /></section><section className="card p-5"><h2 className="mb-3 font-serif text-2xl font-semibold text-amber-200">Panchang at sunrise</h2><PairGrid values={r.panchang} /></section><section className="card p-5"><h2 className="mb-3 font-serif text-xl font-semibold text-rose-300">Ghatak Chakra — traditional caution factors</h2><PairGrid values={r.ghatak} /><p className="mt-3 text-xs text-slate-500">Ghatak factors are used in some muhurta traditions. They do not predict harm by themselves.</p></section></div>;
  } else if (tab === "tara") {
    content = <div className="space-y-5"><section className="card p-5"><h2 className="font-serif text-2xl font-semibold text-amber-200">Tara Chakra</h2><p className="mt-1 text-xs text-slate-500">The 27 nakshatras arranged in nine relationships from your birth star.</p><div className="scroll-thin mt-4 overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-800/50"><tr>{["Tara", "Nakshatra 1", "Nakshatra 2", "Nakshatra 3"].map((h) => <th key={h} className="whitespace-nowrap p-3 text-left text-xs text-slate-400">{h}</th>)}</tr></thead><tbody>{r.tara.map((t, i) => <tr key={t.tara} className={`border-t border-slate-700/40 ${[2,4,6].includes(i) ? "bg-rose-500/5" : ""}`}><td className="p-3 font-semibold text-slate-200">{t.tara}</td>{t.naks.map((n) => <td key={n} className="whitespace-nowrap p-3 text-slate-400">{n}</td>)}</tr>)}</tbody></table></div></section><section className="card p-5"><h2 className="font-serif text-2xl font-semibold text-amber-200">Lucky factors</h2><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4"><Tile label="Days">{r.lucky.days.join(", ")}</Tile><Tile label="Numbers">{r.lucky.numbers.join(", ")}</Tile><Tile label="Colours">{r.lucky.colors.join(", ")}</Tile><Tile label="Direction">{r.lucky.direction}</Tile><Tile label="Life stone">{r.lucky.lifeStone}</Tile><Tile label="Lucky stone">{r.lucky.luckyStone}</Tile><Tile label="Fortune stone">{r.lucky.fortuneStone}</Tile><Tile label="Ishta Devata">{r.lucky.ishtaDevata}</Tile></div><p className="mt-3 text-xs text-slate-500">Gemstones require full ascendant-based analysis. See the Gemstone Calculator before wearing one.</p></section></div>;
  } else if (tab === "remedies") {
    content = <div className="space-y-5"><section className="card p-5"><h2 className="mb-3 font-serif text-2xl font-semibold text-amber-200">Birth-star guidance</h2><RemedyList remedies={r.remedies} /></section><section className="card p-5"><h2 className="font-serif text-xl font-semibold text-violet-200">Nakshatra lord mantra</h2><p className="mt-2 text-lg italic text-slate-200">{PLANET_INFO[r.moon.lord].mantra}</p><p className="mt-1 text-xs text-slate-500">108 repetitions on {PLANET_INFO[r.moon.lord].day}s, if it fits your beliefs.</p></section></div>;
  } else {
    content = <section className="card p-5"><h2 className="font-serif text-2xl font-semibold text-amber-200">Method &amp; limitations</h2><p className="mt-1 text-sm text-slate-400">{r.method}</p><ul className="mt-4 list-disc space-y-3 pl-5 text-sm leading-relaxed text-slate-300">{r.notes.map((n) => <li key={n}>{n}</li>)}</ul><p className="mt-4 text-xs text-slate-500">Engine version {r.version} · calculated {new Date(r.calculatedAt).toLocaleDateString("en-GB", { day:"2-digit", month:"short", year:"numeric", timeZone:"UTC" })}</p></section>;
  }

  return <div><header className="card relative mb-6 overflow-hidden p-6 sm:p-8"><div className="pointer-events-none absolute -right-20 -top-20 h-56 w-56 rounded-full bg-amber-500/10 blur-3xl" /><p className="label-caps !text-amber-300">Saved Nakshatra &amp; Rashi report</p><h1 className="mt-2 font-serif text-4xl font-semibold text-slate-100 sm:text-5xl">{r.chartSummary.name}</h1><p className="mt-2 text-sm text-slate-400">{r.chartSummary.date} · {r.chartSummary.time} · {r.chartSummary.place}</p><div className="mt-4 flex flex-wrap gap-3"><span className="rounded-full bg-amber-500/15 px-4 py-2 text-sm font-bold text-amber-200">{r.moon.nakshatra} · Pada {r.moon.pada}</span><span className="rounded-full bg-violet-500/15 px-4 py-2 text-sm font-bold text-violet-200">Rashi {r.rashi.sanskrit}</span><button type="button" onClick={share} className="rounded-full border border-slate-600 px-4 py-2 text-sm text-slate-300 hover:border-amber-400">{copied ? "Link copied ✓" : "Share this report"}</button><Link href="/calculators/nakshatra-rashi" className="rounded-full border border-amber-400/40 px-4 py-2 text-sm text-amber-200 hover:bg-amber-400/10">New chart</Link></div>{shareFailed && <p className="mt-2 text-xs text-amber-200">Copy this page’s address from your browser to share it.</p>}</header><nav aria-label="Nakshatra report sections" className="scroll-thin mb-6 flex gap-2 overflow-x-auto pb-2">{TABS.map(([k,icon,text]) => <button key={k} type="button" onClick={() => setTab(k)} aria-pressed={tab===k} className={`shrink-0 rounded-xl border px-4 py-2.5 text-sm transition ${tab===k ? "border-amber-400/60 bg-amber-400/15 font-semibold text-amber-200" : "border-slate-700 bg-slate-900/30 text-slate-400 hover:text-slate-200"}`}>{icon} {text}</button>)}</nav><div key={tab} className="animate-pop">{content}</div></div>;
}
